// Hunter talents for Turtle WoW
export const hunterTalents = {
  beastmastery: {
    name: "Beast Mastery",
    icon: "spell_nature_ravenform",
    talents: [
      {
        id: 1,
        name: "Swift Aspects",
        icon: "spell_nature_ravenform",
        ranks: 5,
        row: 1,
        col: 2,
        description: ["Swift AspectsInstantWhile Aspect of the Hawk is active, all normal ranged attacks have a 10% chance of increasing ranged attack speed by ",["$","$L22","1",{"tree":0,"talent":1,"values":["3","6","9","12","15"]}],"% for 12 sec. While Aspect of the Wolf is active, all normal melee attacks have a 10% chance of increasing melee attack speed by ",["$","$L22","2",{"tree":0,"talent":1,"values":["3","6","9","12","15"]}],"% for 12 sec."],
        spellIds: {"rank1":19552,"rank2":19553,"rank3":19554,"rank4":19555,"rank5":19556},
      },
      {
        id: 2,
        name: "Endurance Training",
        icon: "spell_nature_reincarnation",
        ranks: 5,
        row: 1,
        col: 3,
        description: ["Endurance TrainingInstantAdds ",["$","$L22","1",{"tree":0,"talent":2,"values":["6","12","18","24","30"]}],"% of your Stamina to the Stamina of your pets and increases the Health of your pets by ",["$","$L22","2",{"tree":0,"talent":2,"values":["1","2","3","4","5"]}],"%."],
        spellIds: {"rank1":19583,"rank2":19584,"rank3":19585,"rank4":19586,"rank5":19587},
      },
      {
        id: 4,
        name: "Improved Eyes of the Beast",
        icon: "ability_eyeoftheowl",
        ranks: 2,
        row: 2,
        col: 1,
        description: ["Improved Eyes of the BeastInstantIncreases the duration of your Eyes of the Beast by ",["$","$L22","1",{"tree":0,"talent":4,"values":["30000","60000"]}]," sec.\\n\\nWhile channeling Eyes of the Beast, your pet deals ",["$","$L22","2",{"tree":0,"talent":4,"values":["16","31"]}],"% additional damage and gains ",["$","$L22","3",{"tree":0,"talent":4,"values":["16","31"]}],"% increased Focus regeneration."],
        spellIds: {"rank1":19557,"rank2":19558},
      },
      {
        id: 5,
        name: "Improved Primal Aspects",
        icon: "ability_hunter_aspectofthemonkey",
        ranks: 3,
        row: 2,
        col: 2,
        description: ["Improved Primal AspectsInstantIncreases the Dodge bonus of your Aspect of the Monkey by ",["$","$L22","1",{"tree":0,"talent":5,"values":["2","4","6"]}],"%. While Aspect of the Wolf is active, you're healed for ",["$","$L22","2",{"tree":0,"talent":5,"values":["2","4","6"]}],"% of your melee damage."],
        spellIds: {"rank1":19549,"rank2":19550,"rank3":19551},
      },
      {
        id: 6,
        name: "Thick Hide",
        icon: "inv_misc_pelt_bear_03",
        ranks: 3,
        row: 2,
        col: 3,
        description: ["Thick HideInstantAdds ",["$","$L22","1",{"tree":0,"talent":6,"values":["12","24","36"]}],"% of your armor value from items to the armor value of your pets and increases the armor value of your pets by ",["$","$L22","2",{"tree":0,"talent":6,"values":["4","7","10"]}],"%."],
        spellIds: {"rank1":19609,"rank2":19610,"rank3":19612},
      },
      {
        id: 7,
        name: "Improved Revive Pet",
        icon: "ability_hunter_beastsoothe",
        ranks: 2,
        row: 2,
        col: 4,
        description: ["Improved Revive PetInstantRevive Pet's casting time is reduced by ",["$","$L22","1",{"tree":0,"talent":7,"values":["3000","6000"]}]," sec, mana cost is reduced by ",["$","$L22","2",{"tree":0,"talent":7,"values":["20","40"]}],"%, and increases the health your pet returns with by an additional ",["$","$L22","3",{"tree":0,"talent":7,"values":["15","30"]}],"%."],
        spellIds: {"rank1":24443,"rank2":19575},
      },
      {
        id: 8,
        name: "Pathfinding",
        icon: "ability_mount_jungletiger",
        ranks: 2,
        row: 3,
        col: 1,
        description: ["PathfindingInstantIncreases the speed bonus of your Aspect of the Cheetah and Aspect of the Pack by ",["$","$L22","1",{"tree":0,"talent":8,"values":["3","6"]}],"% and increases your pet's movement speed by ",["$","$L22","2",{"tree":0,"talent":8,"values":["15","30"]}],"%."],
        spellIds: {"rank1":19559,"rank2":19560},
      },
      {
        id: 9,
        name: "Coordinated Assault",
        icon: "spell_coordinated_assault_1",
        ranks: 1,
        row: 3,
        col: 2,
        description: "Coordinated AssaultInstantHitting an enemy with Arcane Shot, Steady Shot or Raptor Strike causes your pet's next attack within 6 sec to also perform an attack that deals Physical damage equal to 20% of its Attack Power. This effect can trigger only once every 3 sec.",
        spellIds: {"rank1":49559},
      },
      {
        id: 10,
        name: "Unleashed Fury",
        icon: "ability_bullrush",
        ranks: 5,
        row: 3,
        col: 3,
        description: ["Unleashed FuryInstantIncreases the damage done by your pets by ",["$","$L22","1",{"tree":0,"talent":10,"values":["4","8","12","16","20"]}],"%."],
        spellIds: {"rank1":19616,"rank2":19617,"rank3":19618,"rank4":19619,"rank5":19620},
      },
      {
        id: 12,
        name: "Bestial Discipline",
        icon: "spell_nature_abolishmagic",
        ranks: 2,
        row: 4,
        col: 1,
        description: ["Bestial DisciplineInstantIncreases the Focus regeneration of your pets by ",["$","$L22","1",{"tree":0,"talent":12,"values":["2","5"]}]," each tick and reduces the cooldown of your pets' special ability by ",["$","$L22","2",{"tree":0,"talent":12,"values":["10","20"]}],"%."],
        spellIds: {"rank1":19590,"rank2":19592},
      },
      {
        id: 13,
        name: "Improved Mend Pet",
        icon: "ability_hunter_mendpet",
        ranks: 2,
        row: 4,
        col: 2,
        description: ["Improved Mend PetInstantIncreases amount you heal your pet with Mend Pet by ",["$","$L22","1",{"tree":0,"talent":13,"values":["20","40"]}],"% and gives the spell a ",["$","$L22","2",{"tree":0,"talent":13,"values":["15","50"]}],"% chance of cleansing 1 Curse, Disease, Magic or Poison effect from the pet each tick."],
        spellIds: {"rank1":19572,"rank2":19573},
      },
      {
        id: 14,
        name: "Ferocity",
        icon: "inv_misc_monsterclaw_04",
        ranks: 5,
        row: 4,
        col: 3,
        description: ["FerocityInstantIncreases the critical strike chance of your pets by ",["$","$L22","1",{"tree":0,"talent":14,"values":["3","6","9","12","15"]}],"%."],
        spellIds: {"rank1":19598,"rank2":19599,"rank3":19600,"rank4":19601,"rank5":19602},
      },
      {
        id: 16,
        name: "Intimidation",
        icon: "ability_devour",
        ranks: 1,
        row: 5,
        col: 1,
        description: "Intimidation8% of base mana100 yd rangeInstant60 sec cooldownCommand your pet to intimidate the target on the next successful melee attack, stunning the target for 3 sec, and increasing the pet's threat generation by 50% for 8 sec.",
        spellIds: {"rank1":19577},
      },
      {
        id: 17,
        name: "Kill Command",
        icon: "ability_hunter_killcommand",
        ranks: 1,
        row: 5,
        col: 2,
        description: "Kill Command5% of base mana45 yd rangeInstant12 sec cooldownGive the command to kill, removing any crowd control effects from your pet and causing your pet's next 2 abilities within 10 sec to be guaranteed to critically strike with 80% increased critical strike damage if that ability is capable of striking critically.",
        spellIds: {"rank1":41827},
      },
      {
        id: 19,
        name: "Bestial Precision",
        icon: "ability_druid_rake",
        ranks: 2,
        row: 5,
        col: 4,
        description: ["Bestial PrecisionInstantIncreases the physical hit chance of your pets by ",["$","$L22","1",{"tree":0,"talent":19,"values":["4","8"]}],"% and the spell hit chance of your pets by ",["$","$L22","2",{"tree":0,"talent":19,"values":["9","18"]}],"%. In addition, increases the weapon skill of your pets by ",["$","$L22","3",{"tree":0,"talent":19,"values":["5.","10."]}]],
        spellIds: {"rank1":51554,"rank2":51555},
      },
      {
        id: 20,
        name: "Spirit Bond",
        icon: "ability_druid_demoralizingroar",
        ranks: 2,
        row: 6,
        col: 1,
        description: ["Spirit BondInstantYour pet gains melee attack power equal to ",["$","$L22","1",{"tree":0,"talent":20,"values":["12","25"]}],"% of your ranged attack power and spell power equal to ",["$","$L22","2",{"tree":0,"talent":20,"values":["7","15"]}],"% of your ranged attack power. While your pet is active, you and your pet will regenerate ",["$","$L22","3",{"tree":0,"talent":20,"values":["1","2"]}],"% of total health every 5 sec."],
        spellIds: {"rank1":19578,"rank2":20895},
      },
      {
        id: 22,
        name: "Frenzy",
        icon: "inv_misc_monsterclaw_03",
        ranks: 5,
        row: 6,
        col: 3,
        description: ["FrenzyInstantGives your pet a ",["$","$L22","1",{"tree":0,"talent":22,"values":["20","40","60","80","100"]}],"% chance to gain a 30% attack speed increase for 8 sec after dealing a critical strike."],
        requires: 14,
        reqRanks: 5,
        spellIds: {"rank1":19621,"rank2":19622,"rank3":19623,"rank4":19624,"rank5":19625},
      },
      {
        id: 25,
        name: "Baited Shot",
        icon: "inv_misc_food_66",
        ranks: 1,
        row: 7,
        col: 2,
        description: "Baited Shot7% of base mana35 yd range-1000 sec cast8 sec cooldownAn instant shot that deals 125% weapon damage and attaches a bait to the target. The target takes 15% more damage from your pet and your pet's attacks to the target generate 5 Focus for 8 sec. Can only be used after your pet critically strikes a target and Focus generation can trigger only once every 2 sec.",
        requires: 17,
        reqRanks: 1,
        spellIds: {"rank1":46321},
      }
    ]
  },
  marksmanship: {
    name: "Marksmanship",
    icon: "spell_frost_stun",
    talents: [
      {
        id: 1,
        name: "Improved Concussive Shot",
        icon: "spell_frost_stun",
        ranks: 5,
        row: 1,
        col: 2,
        description: ["Improved Concussive ShotInstantGives your Concussive Shot a ",["$","$L22","1",{"tree":1,"talent":1,"values":["4","8","12","16","20"]}],"% chance to stun the target for 3 sec."],
        spellIds: {"rank1":19407,"rank2":19412,"rank3":19413,"rank4":19414,"rank5":19415},
      },
      {
        id: 2,
        name: "Efficiency",
        icon: "spell_frost_wizardmark",
        ranks: 5,
        row: 1,
        col: 3,
        description: ["EfficiencyInstantReduces the Mana cost of your Shots and Stings by ",["$","$L22","1",{"tree":1,"talent":2,"values":["2","4","6","8","10"]}],"%. Aimed Shot, Arcane Shot and Serpent Sting also have approximately 30% lower base mana cost at all ranks (balance change)."],
        spellIds: {"rank1":19416,"rank2":19417,"rank3":19418,"rank4":19419,"rank5":19420},
      },
      {
        id: 5,
        name: "Improved Stings",
        icon: "ability_hunter_quickshot",
        ranks: 5,
        row: 2,
        col: 2,
        description: ["Improved StingsInstantIncreases the damage done by your Serpent Sting by ",["$","$L22","1",{"tree":1,"talent":5,"values":["6","12","18","24","30"]}],"% and increases the mana drained by Viper Sting by ",["$","$L22","2",{"tree":1,"talent":5,"values":["1","2","3","4","5"]}],"%."],
        spellIds: {"rank1":19464,"rank2":19465,"rank3":19466,"rank4":19467,"rank5":19468},
      },
      {
        id: 6,
        name: "Lethal Shots",
        icon: "ability_searingarrow",
        ranks: 5,
        row: 2,
        col: 3,
        description: ["Lethal ShotsInstantIncreases your critical strike chance with ranged weapons by ",["$","$L22","1",{"tree":1,"talent":6,"values":["1","2","3","4","5"]}],"%."],
        spellIds: {"rank1":19426,"rank2":19427,"rank3":19429,"rank4":19430,"rank5":19431},
      },
      {
        id: 8,
        name: "Hawk Eye",
        icon: "ability_townwatch",
        ranks: 2,
        row: 3,
        col: 1,
        description: ["Hawk EyeInstantIncreases the range of your ranged weapons by ",["$","$L22","1",{"tree":1,"talent":8,"values":["3","6"]}]," yards."],
        spellIds: {"rank1":19498,"rank2":19499},
      },
      {
        id: 9,
        name: "Improved Scorpid Sting",
        icon: "ability_hunter_criticalshot",
        ranks: 2,
        row: 3,
        col: 2,
        description: ["Improved Scorpid StingInstantScorpid String reduces enemy attack speed by an additional ",["$","$L22","1",{"tree":1,"talent":9,"values":["5","10"]}],"% and reduces their damage done by an additional ",["$","$L22","2",{"tree":1,"talent":9,"values":["1","2"]}],"%."],
        spellIds: {"rank1":19491,"rank2":19493},
      },
      {
        id: 11,
        name: "Steady Shot",
        icon: "ability_hunter_steadyshot",
        ranks: 1,
        row: 3,
        col: 4,
        description: "Steady Shot% of base mana35 yd range1 sec castA precise shot with a ranged weapon that strikes the target for 60% weapon damage plus an additional 10 damage.",
        spellIds: {"rank1":3035},
      },
      {
        id: 12,
        name: "Improved Hunter's Mark",
        icon: "ability_hunter_snipershot",
        ranks: 3,
        row: 4,
        col: 1,
        description: ["Improved Hunter's MarkInstantIncreases the Ranged Attack Power bonus of your Hunter's Mark spell by ",["$","$L22","1",{"tree":1,"talent":12,"values":["5","10","15"]}],"%."],
        spellIds: {"rank1":19421,"rank2":19422,"rank3":19423},
      },
      {
        id: 13,
        name: "Swiftshot",
        icon: "ability_impalingbolt",
        ranks: 3,
        row: 4,
        col: 2,
        description: ["SwiftshotInstantReduces the cooldown of your Arcane Shot and Aimed Shot by ",["$","$L22","1",{"tree":1,"talent":13,"values":["300","600","1000"]}]," sec."],
        spellIds: {"rank1":19454,"rank2":19455,"rank3":19456},
      },
      {
        id: 14,
        name: "Mortal Shots",
        icon: "ability_piercedamage",
        ranks: 5,
        row: 4,
        col: 3,
        description: ["Mortal ShotsInstantIncreases your ranged weapon critical strike damage bonus by ",["$","$L22","1",{"tree":1,"talent":14,"values":["6","12","18","24","30"]}],"%."],
        requires: 6,
        reqRanks: 5,
        spellIds: {"rank1":19485,"rank2":19487,"rank3":19488,"rank4":19489,"rank5":19490},
      },
      {
        id: 16,
        name: "Scatter Shot",
        icon: "ability_golemstormbolt",
        ranks: 1,
        row: 5,
        col: 1,
        description: "Scatter Shot8% of base mana15 yd range-1000 sec cast30 sec cooldownA short-range shot that deals 50% weapon damage and disorients the target for 4 sec. Any damage caused will remove the effect. Turns off your attack when used.",
        spellIds: {"rank1":19503},
      },
      {
        id: 17,
        name: "Barrage",
        icon: "ability_upgrademoonglaive",
        ranks: 3,
        row: 5,
        col: 2,
        description: ["BarrageInstantIncreases the damage done by your Multi-Shot and Volley spells by ",["$","$L22","1",{"tree":1,"talent":17,"values":["5","10","15"]}],"%."],
        spellIds: {"rank1":19461,"rank2":19462,"rank3":24691},
      },
      {
        id: 18,
        name: "Piercing Shots",
        icon: "ability_hunter_disarmingshot",
        ranks: 2,
        row: 5,
        col: 3,
        description: ["Piercing ShotsInstantYour critical strikes from Multi-Shot, Steady Shot and Aimed Shot cause the target to bleed, dealing ",["$","$L22","1",{"tree":1,"talent":18,"values":["15","30"]}],"% of the damage over 8 sec. This damage generates no threat."],
        spellIds: {"rank1":51512,"rank2":51513},
      },
      {
        id: 19,
        name: "Improved Steady Shot",
        icon: "ability_hunter_improvedsteadyshot",
        ranks: 2,
        row: 5,
        col: 4,
        description: "Improved Steady ShotInstantIncreases the damage done by your Steady Shot by 8%.",
        requires: 11,
        reqRanks: 1,
        spellIds: {"rank1":51515,"rank2":51516},
      },
      {
        id: 20,
        name: "Endless Quiver",
        icon: "inv_misc_quiver_03",
        ranks: 2,
        row: 6,
        col: 1,
        description: ["Endless QuiverInstantYour Auto Shot, Arcane Shot, Steady Shot and Multi-Shot have a ",["$","$L22","1",{"tree":1,"talent":20,"values":["3","6"]}],"% chance to fire an additional normal ranged attack. This additional shot does not spend ammo."],
        spellIds: {"rank1":51517,"rank2":51518},
      },
      {
        id: 22,
        name: "Ranged Weapon Specialization",
        icon: "inv_weapon_rifle_06",
        ranks: 5,
        row: 6,
        col: 3,
        description: ["Ranged Weapon SpecializationInstantIncreases the damage you deal with ranged weapons by ",["$","$L22","1",{"tree":1,"talent":22,"values":["1","2","3","4","5"]}],"%."],
        spellIds: {"rank1":19507,"rank2":19508,"rank3":19509,"rank4":19510,"rank5":19511},
      },
      {
        id: 25,
        name: "Trueshot Aura",
        icon: "ability_trueshot",
        ranks: 1,
        row: 7,
        col: 2,
        description: "Trueshot AuraInstantIncreases the attack power of party members within 45 yards by 3%, plus an additional 30. The aura lasts until canceled.",
        requires: 17,
        reqRanks: 3,
        spellIds: {"rank1":19506},
      }
    ]
  },
  survival: {
    name: "Survival",
    icon: "spell_holy_prayerofhealing",
    talents: [
      {
        id: 0,
        name: "Improved Slaying",
        icon: "spell_holy_prayerofhealing",
        ranks: 3,
        row: 1,
        col: 1,
        description: ["Improved SlayingInstantIncreases all damage caused against Beasts, Giants, Dragonkin, and Humanoid targets by ",["$","$L22","1",{"tree":2,"talent":0,"values":["1","2","3"]}],"% and increases critical damage caused against Beasts, Giants, Dragonkin, and Humanoid targets by an additional ",["$","$L22","2",{"tree":2,"talent":0,"values":["1","2","3"]}],"%."],
        spellIds: {"rank1":45977,"rank2":45978,"rank3":45979},
      },
      {
        id: 1,
        name: "Resourcefulness",
        icon: "inv_misc_book_08",
        ranks: 5,
        row: 1,
        col: 2,
        description: ["ResourcefulnessInstantReduces the Mana cost of all traps and melee abilities by ",["$","$L22","1",{"tree":2,"talent":1,"values":["2","4","6","8","10"]}],"%."],
        spellIds: {"rank1":51570,"rank2":51571,"rank3":51572,"rank4":51573,"rank5":51574},
      },
      {
        id: 2,
        name: "Swift Reflexes",
        icon: "ability_parry",
        ranks: 2,
        row: 1,
        col: 3,
        description: ["Swift ReflexesInstantIncreases your Parry chance and attack speed by ",["$","$L22","1",{"tree":2,"talent":2,"values":["1","2"]}],"%."],
        spellIds: {"rank1":19295,"rank2":19297},
      },
      {
        id: 4,
        name: "Entrapment",
        icon: "spell_nature_stranglevines",
        ranks: 3,
        row: 2,
        col: 1,
        description: ["EntrapmentInstantGives your Immolation Trap, Frost Trap, and Explosive Trap a ",["$","$L22","1",{"tree":2,"talent":4,"values":["8","16","25"]}],"% chance to entrap the target, preventing them from moving for 5 sec."],
        spellIds: {"rank1":19184,"rank2":19387,"rank3":19388},
      },
      {
        id: 5,
        name: "Savage Strikes",
        icon: "ability_racial_bloodrage",
        ranks: 2,
        row: 2,
        col: 2,
        description: ["Savage StrikesInstantIncreases the damage done by your offhand weapon by ",["$","$L22","1",{"tree":2,"talent":5,"values":["13","25"]}],"% and the critical strike chance of your Lacerate, Raptor Strike, Mongoose Bite, Carve and Wing Clip abilities by ",["$","$L22","2",{"tree":2,"talent":5,"values":["3","6"]}],"%."],
        spellIds: {"rank1":19159,"rank2":19160},
      },
      {
        id: 6,
        name: "Improved Wing Clip",
        icon: "ability_rogue_trip",
        ranks: 3,
        row: 2,
        col: 3,
        description: ["Improved Wing ClipInstantGives your Wing Clip ability a ",["$","$L22","1",{"tree":2,"talent":6,"values":["14","28","40"]}],"% chance to immobilize the target for 5 sec."],
        spellIds: {"rank1":19228,"rank2":19232,"rank3":19233},
      },
      {
        id: 8,
        name: "Planning Ahead",
        icon: "inv_misc_map_01",
        ranks: 2,
        row: 3,
        col: 1,
        description: ["Planning AheadInstantThe duration of Freezing and Frost Trap effects and the damage of Immolation and Explosive Trap effects are increased by ",["$","$L22","1",{"tree":2,"talent":8,"values":["13","25"]}],"% if the traps are not triggered within the first 5 sec after being placed."],
        spellIds: {"rank1":51576,"rank2":51577},
      },
      {
        id: 9,
        name: "Survivalist",
        icon: "trade_survival",
        ranks: 5,
        row: 3,
        col: 2,
        description: ["SurvivalistInstantIncreases total health by ",["$","$L22","1",{"tree":2,"talent":9,"values":["2","4","6","8","10"]}],"%."],
        spellIds: {"rank1":19255,"rank2":19256,"rank3":19257,"rank4":19258,"rank5":19259},
      },
      {
        id: 10,
        name: "Carve",
        icon: "inv_throwingknife_06",
        ranks: 1,
        row: 3,
        col: 3,
        description: "Carve% of base manaInstantA sweeping attack that strikes up to 5 enemies in a 10 yard cone in front of you, dealing 60% weapon damage.\\nThis ability shares a cooldown with Multi-Shot.",
        spellIds: {"rank1":51575},
      },
      {
        id: 11,
        name: "Deterrence",
        icon: "ability_whirlwind",
        ranks: 1,
        row: 3,
        col: 4,
        description: "DeterrenceInstant300 sec cooldownWhen activated, increases your Dodge and Parry chance by 25% for 10 sec.",
        spellIds: {"rank1":19263},
      },
      {
        id: 12,
        name: "Stinging Nettle",
        icon: "inv_misc_herb_16",
        ranks: 2,
        row: 4,
        col: 1,
        description: ["Stinging NettleInstantYour Mongoose Bite and triggered Fire traps now apply your highest rank of Serpent Sting for ",["$","$L22","1",{"tree":2,"talent":12,"values":["20","40"]}],"% of the duration. Serpent Stings applied this way ignore resistances and immunities."],
        spellIds: {"rank1":51579,"rank2":51580},
      },
      {
        id: 13,
        name: "Surefooted",
        icon: "ability_kick",
        ranks: 3,
        row: 4,
        col: 2,
        description: ["SurefootedInstantIncreases hit chance by ",["$","$L22","1",{"tree":2,"talent":13,"values":["1","2","3"]}],"% and increases the chance movement impairing effects will be resisted by an additional ",["$","$L22","2",{"tree":2,"talent":13,"values":["5","10","15"]}],"%."],
        spellIds: {"rank1":19290,"rank2":19294,"rank3":24283},
      },
      {
        id: 15,
        name: "Improved Feign Death",
        icon: "ability_rogue_feigndeath",
        ranks: 2,
        row: 4,
        col: 4,
        description: ["Improved Feign DeathInstantReduces the chance your Feign Death ability will be resisted by ",["$","$L22","1",{"tree":2,"talent":15,"values":["4","8"]}],"%."],
        spellIds: {"rank1":19286,"rank2":19287},
      },
      {
        id: 16,
        name: "Killer Instinct",
        icon: "spell_holy_blessingofstamina",
        ranks: 3,
        row: 5,
        col: 1,
        description: ["Killer InstinctInstantIncreases your critical strike chance with all attacks by ",["$","$L22","1",{"tree":2,"talent":16,"values":["1","2","3"]}],"%, increases your melee critical strike damage bonus by ",["$","$L22","2",{"tree":2,"talent":16,"values":["7","14","20"]}],"%."],
        spellIds: {"rank1":19370,"rank2":19371,"rank3":19373},
      },
      {
        id: 17,
        name: "Trap Mastery",
        icon: "ability_ensnare",
        ranks: 3,
        row: 5,
        col: 2,
        description: ["Trap MasteryInstantIncreases the duration of Freezing and Frost Trap effects by ",["$","$L22","1",{"tree":2,"talent":17,"values":["10","20","30"]}],"% and the damage of Immolation and Explosive Trap effects by ",["$","$L22","2",{"tree":2,"talent":17,"values":["10","20","30"]}],"%. In addition, reduces the chance that enemies will resist trap effects by ",["$","$L22","3",{"tree":2,"talent":17,"values":["4","7","10"]}],"%."],
        spellIds: {"rank1":19376,"rank2":19377,"rank3":51581},
      },
      {
        id: 18,
        name: "Lacerate",
        icon: "spell_lacerate_1c",
        ranks: 1,
        row: 5,
        col: 3,
        description: "Lacerate8% of base mana5 yd rangeInstant10 sec cooldownDeepen your target's open wound, dealing damage equal to 35% of your melee Attack Power and bleeding them for 20% of the damage over 8 sec. Can only be used after critically striking your target. Using this ability from the sides of your target increases its damage by 10% and causes the bleed to deal its total damage 100% faster.",
        requires: 10,
        reqRanks: 1,
        spellIds: {"rank1":48049},
      },
      {
        id: 20,
        name: "Vicious Strikes",
        icon: "ability_hunter_swiftstrike",
        ranks: 2,
        row: 6,
        col: 1,
        description: ["Vicious StrikesInstantReduces the cooldown of your Raptor Strike and Mongoose Bite abilities by ",["$","$L22","1",{"tree":2,"talent":20,"values":["1000","2000"]}]," sec and increases the damage they deal by ",["$","$L22","2",{"tree":2,"talent":20,"values":["5","10"]}],"%."],
        spellIds: {"rank1":51584,"rank2":51585},
      },
      {
        id: 22,
        name: "Lightning Reflexes",
        icon: "spell_nature_invisibilty",
        ranks: 5,
        row: 6,
        col: 3,
        description: ["Lightning ReflexesInstantIncreases your Agility by ",["$","$L22","1",{"tree":2,"talent":22,"values":["2","4","6","8","10"]}],"% and increases your melee attack power by an amount equal to ",["$","$L22","2",{"tree":2,"talent":22,"values":["20","40","60","80","100"]}],"% of your Agility."],
        spellIds: {"rank1":19168,"rank2":19180,"rank3":19181,"rank4":24296,"rank5":24297},
      },
      {
        id: 25,
        name: "Untamed Trapper",
        icon: "spell_nature_slow",
        ranks: 1,
        row: 7,
        col: 2,
        description: "Untamed TrapperInstantReduces the mana cost of your Immolation Trap and Explosive Trap effects by 20% and increases their damage based on your melee Attack Power. In addition, all traps can be placed while in combat.",
        requires: 17,
        reqRanks: 3,
        spellIds: {"rank1":51586},
      }
    ]
  }
};
