// Mage talents for Turtle WoW
export const mageTalents = {
  arcane: {
    name: "Arcane",
    icon: "spell_holy_dispelmagic",
    talents: [
      {
        id: 0,
        name: "Arcane Subtlety",
        icon: "spell_holy_dispelmagic",
        ranks: 2,
        row: 1,
        col: 1,
        description: ["Arcane SubtletyInstantReduces your target's resistance to all your spells by ",["$","$L22","1",{"tree":0,"talent":0,"values":["5","10"]}]," and reduces the threat caused by your Arcane spells by ",["$","$L22","2",{"tree":0,"talent":0,"values":["20","40"]}],"%."],
        spellIds: {"rank1":11210,"rank2":12592},
      },
      {
        id: 1,
        name: "Magic Absorption",
        icon: "spell_nature_astralrecalgroup",
        ranks: 3,
        row: 1,
        col: 2,
        description: ["Magic AbsorptionInstantIncreases all resistances by ",["$","$L22","1",{"tree":0,"talent":1,"values":["4","7","10"]}]," and whenever one of your spells is partially or fully resisted you restore ",["$","$L22","2",{"tree":0,"talent":1,"values":["1","2","3"]}],"% of your maximum mana. This effect can occur once every 2 sec."],
        spellIds: {"rank1":29441,"rank2":29444,"rank3":29445},
      },
      {
        id: 2,
        name: "Improved Arcane Missiles",
        icon: "spell_nature_starfall",
        ranks: 5,
        row: 1,
        col: 3,
        description: ["Improved Arcane MissilesInstantGives you a ",["$","$L22","1",{"tree":0,"talent":2,"values":["20","40","60","80","100"]}],"% chance to avoid interruption caused by damage while channeling Arcane Missiles."],
        spellIds: {"rank1":11237,"rank2":12463,"rank3":12464,"rank4":16769,"rank5":16770},
      },
      {
        id: 4,
        name: "Wand Specialization",
        icon: "inv_wand_01",
        ranks: 2,
        row: 2,
        col: 1,
        description: ["Wand SpecializationInstantIncreases your damage and chance to hit with Wands by ",["$","$L22","1",{"tree":0,"talent":4,"values":["13","25"]}],"% and ",["$","$L22","2",{"tree":0,"talent":4,"values":["5","10"]}],"%, respectively. Successful Wand attacks have a chance to restore 0 mana."],
        spellIds: {"rank1":6057,"rank2":6085},
      },
      {
        id: 5,
        name: "Arcane Focus",
        icon: "spell_holy_devotion",
        ranks: 5,
        row: 2,
        col: 2,
        description: ["Arcane FocusInstantReduces the chance that the opponent can resist your Arcane spells by ",["$","$L22","1",{"tree":0,"talent":5,"values":["2","4","6","8","10"]}],"%."],
        spellIds: {"rank1":11222,"rank2":12839,"rank3":12840,"rank4":12841,"rank5":12842},
      },
      {
        id: 6,
        name: "Arcane Concentration",
        icon: "spell_shadow_manaburn",
        ranks: 5,
        row: 2,
        col: 3,
        description: ["Arcane ConcentrationInstantGives you a ",["$","$L22","1",{"tree":0,"talent":6,"values":["2","4","6","8","10"]}],"% chance of entering a Clearcasting state after any damage spell hits a target. The Clearcasting state reduces the mana cost of your next damage spell by 1000%. This effect can occur once every 8 sec."],
        spellIds: {"rank1":11213,"rank2":12574,"rank3":12575,"rank4":12576,"rank5":12577},
      },
      {
        id: 8,
        name: "Magic Attunement",
        icon: "spell_nature_abolishmagic",
        ranks: 1,
        row: 3,
        col: 1,
        description: "Magic AttunementInstantIncreases the effect of your Amplify Magic and Dampen Magic spells by 100% and allows them to be cast on enemies. Only affects targets level 62 or lower.",
        spellIds: {"rank1":11247},
      },
      {
        id: 9,
        name: "Arcane Impact",
        icon: "spell_nature_wispsplode",
        ranks: 3,
        row: 3,
        col: 2,
        description: ["Arcane ImpactInstantIncreases the critical strike chance of your Arcane spells by an additional ",["$","$L22","1",{"tree":0,"talent":9,"values":["2","4","6"]}],"%."],
        spellIds: {"rank1":11242,"rank2":12467,"rank3":12469},
      },
      {
        id: 10,
        name: "Arcane Rupture",
        icon: "spell_arcane_blast",
        ranks: 1,
        row: 3,
        col: 3,
        description: "Arcane Rupture mana30 yd range2.5 sec castRupture your target with the force of concentrated arcane energy, dealing 101 to 115 Arcane damage and increasing the damage and mana cost of your Arcane Missiles spell by 20% for 8 sec.",
        spellIds: {"rank1":51949},
      },
      {
        id: 12,
        name: "Improved Mana Shield",
        icon: "spell_shadow_detectlesserinvisibility",
        ranks: 2,
        row: 4,
        col: 1,
        description: ["Improved Mana ShieldInstantDecreases the mana lost per point of damage taken when Mana Shield is active by ",["$","$L22","1",{"tree":0,"talent":12,"values":["13","25"]}],"%."],
        spellIds: {"rank1":11252,"rank2":12605},
      },
      {
        id: 13,
        name: "Improved Counterspell",
        icon: "spell_frost_iceshock",
        ranks: 2,
        row: 4,
        col: 2,
        description: "Improved CounterspellInstantGives your Counterspell a 50% chance to silence the target for 4 sec.",
        spellIds: {"rank1":11255,"rank2":12598},
      },
      {
        id: 14,
        name: "Temporal Convergence",
        icon: "spell_nature_stormreach",
        ranks: 3,
        row: 4,
        col: 3,
        description: ["Temporal ConvergenceInstantYour Arcane Missiles have a chance of ",["$","$L22","1",{"tree":0,"talent":14,"values":["5","10","15"]}],"% to reset the cooldown of Arcane Rupture and cause it to return its base mana cost on its next cast. This effect can occur once every 15 sec."],
        spellIds: {"rank1":51963,"rank2":51964,"rank3":51965},
        requires: 10,
        reqRanks: 1,
      },
      {
        id: 15,
        name: "Arcane Meditation",
        icon: "spell_shadow_siphonmana",
        ranks: 3,
        row: 4,
        col: 4,
        description: ["Arcane MeditationInstantAllows ",["$","$L22","1",{"tree":0,"talent":15,"values":["7","14","20"]}],"% of your Mana regeneration to continue while casting. This effect is tripled while below 35% total mana."],
        spellIds: {"rank1":18462,"rank2":18463,"rank3":18464},
      },
      {
        id: 16,
        name: "Arcane Instability",
        icon: "spell_shadow_teleport",
        ranks: 3,
        row: 5,
        col: 1,
        description: ["Arcane InstabilityInstantYour successful damaging Arcane spells have an ",["$","$L22","1",{"tree":0,"talent":16,"values":["8","16","25"]}],"% chance to uncontrollably erupt, consuming 2% of your base mana to deal 25% more damage."],
        spellIds: {"rank1":15058,"rank2":15059,"rank3":15060},
      },
      {
        id: 17,
        name: "Presence of Mind",
        icon: "spell_nature_enchantarmor",
        ranks: 1,
        row: 5,
        col: 2,
        description: "Presence of MindInstantWhen activated, your next Mage spell with a casting time less than 10 sec becomes an instant cast spell.",
        spellIds: {"rank1":12043},
      },
      {
        id: 18,
        name: "Accelerated Arcana",
        icon: "spell_arcane_portaldarnassus",
        ranks: 1,
        row: 5,
        col: 3,
        description: "Accelerated ArcanaInstantIncreases the casting speed of your Arcane spells by 5%. In addition, casting speed increase effects increase the cooldown recovery speed of your Arcane spells and the tick speed of your Arcane Missiles, reducing their duration.",
        spellIds: {"rank1":51981},
      },
      {
        id: 19,
        name: "Arcane Potency",
        icon: "inv_enchant_essencemagiclarge",
        ranks: 2,
        row: 5,
        col: 4,
        description: ["Arcane PotencyInstantIncreases the critical strike damage bonus of your Arcane spells by ",["$","$L22","1",{"tree":0,"talent":19,"values":["50","100"]}],"%."],
        spellIds: {"rank1":45403,"rank2":45404},
      },
      {
        id: 22,
        name: "Resonance Cascade",
        icon: "spell_mage_focusingcrystal",
        ranks: 5,
        row: 6,
        col: 3,
        description: ["Resonance CascadeInstantYour successful damaging Arcane spells have a ",["$","$L22","1",{"tree":0,"talent":22,"values":["4","8","12","16","20"]}],"% chance to duplicate for 50% of the damage. This effect can trigger off of itself and duplicated Arcane Missiles are channeled in tandem with the original cast."],
        spellIds: {"rank1":51262,"rank2":51987,"rank3":51988,"rank4":51989,"rank5":51990},
      },
      {
        id: 25,
        name: "Arcane Power",
        icon: "spell_nature_lightning",
        ranks: 1,
        row: 7,
        col: 2,
        description: "Arcane PowerInstant180 sec cooldownWhen activated, your casting speed is increased by 30% while draining 1% of your maximum mana every second and reducing all mana gain by 50%.\nFalling below 10% maximum mana causes you to violently combust from uncontrollable power, killing you instantly. Lasts 20 sec and cannot be cancelled.",
        spellIds: {"rank1":12042},
        requires: 17,
        reqRanks: 1,
      }
    ]
  },
  fire: {
    name: "Fire",
    icon: "spell_fire_flamebolt",
    talents: [
      {
        id: 1,
        name: "Improved Fireball",
        icon: "spell_fire_flamebolt",
        ranks: 5,
        row: 1,
        col: 2,
        description: ["Improved FireballInstantReduces the casting time of your Fireball spell by ",["$","$L22","1",{"tree":1,"talent":1,"values":["100","200","300","400","500"]}]," sec."],
        spellIds: {"rank1":11069,"rank2":12338,"rank3":12339,"rank4":12340,"rank5":12341},
      },
      {
        id: 2,
        name: "Impact",
        icon: "spell_fire_meteorstorm",
        ranks: 5,
        row: 1,
        col: 3,
        description: ["ImpactInstantGives your Fire spells a ",["$","$L22","1",{"tree":1,"talent":2,"values":["2","4","6","8","10"]}],"% chance to stun the target for 2 sec."],
        spellIds: {"rank1":11103,"rank2":12357,"rank3":12358,"rank4":12359,"rank5":12360},
      },
      {
        id: 4,
        name: "Ignite",
        icon: "spell_fire_incinerate",
        ranks: 5,
        row: 2,
        col: 1,
        description: ["IgniteInstantYour critical strikes from Fire damage spells cause the target to burn for an additional ",["$","$L22","1",{"tree":1,"talent":4,"values":["8","16","24","32","40"]}],"% of your spell's damage over 4 sec."],
        spellIds: {"rank1":11119,"rank2":11120,"rank3":12846,"rank4":12847,"rank5":12848},
      },
      {
        id: 5,
        name: "Flame Throwing",
        icon: "spell_fire_flare",
        ranks: 2,
        row: 2,
        col: 2,
        description: "Flame ThrowingInstantIncreases the range of your Fire spells by 6 yards and the radius of your Blast Wave by 20%.",
        spellIds: {"rank1":11100,"rank2":12353},
      },
      {
        id: 6,
        name: "Improved Fire Blast",
        icon: "spell_fire_fireball",
        ranks: 3,
        row: 2,
        col: 3,
        description: ["Improved Fire BlastInstantReduces the cooldown of your Fire Blast spell by ",["$","$L22","1",{"tree":1,"talent":6,"values":["500","1000","1500"]}]," sec and reduces the global cooldown of your Fire Blast spell by ",["$","$L22","2",{"tree":1,"talent":6,"values":["300","600","1000"]}]," sec."],
        spellIds: {"rank1":11078,"rank2":11080,"rank3":12342},
      },
      {
        id: 8,
        name: "Incinerate",
        icon: "spell_fire_flameshock",
        ranks: 2,
        row: 3,
        col: 1,
        description: ["IncinerateInstantIncreases the critical strike chance of your Fire Blast and Scorch spells by ",["$","$L22","1",{"tree":1,"talent":8,"values":["2","4"]}],"%."],
        spellIds: {"rank1":18459,"rank2":18460},
      },
      {
        id: 9,
        name: "Improved Flamestrike",
        icon: "spell_fire_selfdestruct",
        ranks: 3,
        row: 3,
        col: 2,
        description: ["Improved FlamestrikeInstantIncreases the critical strike chance of your Flamestrike spell by ",["$","$L22","1",{"tree":1,"talent":9,"values":["5","10","15"]}],"%."],
        spellIds: {"rank1":11108,"rank2":12349,"rank3":12350},
      },
      {
        id: 10,
        name: "Pyroblast",
        icon: "spell_fire_fireball02",
        ranks: 1,
        row: 3,
        col: 3,
        description: "Pyroblast mana35 yd range6 sec castHurls an immense fiery boulder that causes 141 to 188 Fire damage and an additional 56 Fire damage over 12 sec.",
        spellIds: {"rank1":11366},
      },
      {
        id: 11,
        name: "Burning Soul",
        icon: "spell_fire_fire",
        ranks: 2,
        row: 3,
        col: 4,
        description: "Burning SoulInstantGives your Fire spells a 70% chance to not lose casting time when you take damage and reduces the threat caused by your Fire spells by 30%.",
        spellIds: {"rank1":11083,"rank2":12351},
      },
      {
        id: 12,
        name: "Fire Vulnerability",
        icon: "spell_fire_soulburn",
        ranks: 3,
        row: 4,
        col: 1,
        description: ["Fire VulnerabilityInstantYour Scorch and Fire Blast spells have a ",["$","$L22","1",{"tree":1,"talent":12,"values":["33","66","100"]}],"% chance to cause your target to be vulnerable to Fire damage. This vulnerability increases the Fire damage dealt to your target by 3% and lasts 30 sec. Stacks up to 30001 times."],
        spellIds: {"rank1":11095,"rank2":12872,"rank3":12873},
      },
      {
        id: 13,
        name: "Improved Fire Ward",
        icon: "spell_fire_firearmor",
        ranks: 2,
        row: 4,
        col: 2,
        description: ["Improved Fire WardInstantCauses your Fire Ward to have a ",["$","$L22","1",{"tree":1,"talent":13,"values":["10","20"]}],"% chance to reflect Fire spells while active."],
        spellIds: {"rank1":11094,"rank2":13043},
      },
      {
        id: 15,
        name: "Master of Elements",
        icon: "spell_fire_masterofelements",
        ranks: 3,
        row: 4,
        col: 4,
        description: ["Master of ElementsInstantYour Fire and Frost spell criticals will refund ",["$","$L22","1",{"tree":1,"talent":15,"values":["15","30","45"]}],"% of their base mana cost."],
        spellIds: {"rank1":29074,"rank2":29075,"rank3":29076},
      },
      {
        id: 16,
        name: "Blast Wave",
        icon: "spell_holy_excorcism_02",
        ranks: 1,
        row: 5,
        col: 1,
        description: "Blast Wave manaInstantA wave of flame radiates outward from the caster, damaging all enemies caught within the 10 yard blast for 154 to 187 Fire damage, and dazing them for 6 sec.",
        spellIds: {"rank1":11113},
      },
      {
        id: 17,
        name: "Critical Mass",
        icon: "spell_nature_wispheal",
        ranks: 3,
        row: 5,
        col: 2,
        description: ["Critical MassInstantIncreases the critical strike chance of your Fire spells by ",["$","$L22","1",{"tree":1,"talent":17,"values":["2","4","6"]}],"%."],
        spellIds: {"rank1":11115,"rank2":11367,"rank3":11368},
      },
      {
        id: 18,
        name: "Hot Streak",
        icon: "ability_mage_firestarter",
        ranks: 2,
        row: 5,
        col: 3,
        description: "Hot StreakInstantGives your Fireball and Fire Blast critical strikes a 50% chance to grant Hot Streak, reducing the cast time of your next Pyroblast by 1000 sec per stack for 180 sec. Stacks up to 180001 times.",
        spellIds: {"rank1":51927,"rank2":51928},
        requires: 10,
        reqRanks: 1,
      },
      {
        id: 22,
        name: "Fire Power",
        icon: "spell_fire_immolation",
        ranks: 5,
        row: 6,
        col: 3,
        description: ["Fire PowerInstantIncreases the damage done by your Fire spells by ",["$","$L22","1",{"tree":1,"talent":22,"values":["2","4","6","8","10"]}],"%."],
        spellIds: {"rank1":11124,"rank2":12378,"rank3":12398,"rank4":12399,"rank5":12400},
      },
      {
        id: 25,
        name: "Combustion",
        icon: "spell_fire_sealoffire",
        ranks: 1,
        row: 7,
        col: 2,
        description: "CombustionInstantWhen activated, this spell causes each of your Fire damage spell hits to increase your critical strike chance with Fire damage spells by 10%. This effect lasts until you have caused 3 critical strikes with Fire spells.",
        spellIds: {"rank1":11129},
        requires: 17,
        reqRanks: 3,
      }
    ]
  },
  frost: {
    name: "Frost",
    icon: "spell_frost_frostward",
    talents: [
      {
        id: 0,
        name: "Frost Warding",
        icon: "spell_frost_frostward",
        ranks: 2,
        row: 1,
        col: 1,
        description: ["Frost WardingInstantIncreases the armor and resistances given by your Frost Armor and Ice Armor spells by ",["$","$L22","1",{"tree":2,"talent":0,"values":["15","30"]}],"%. In addition, gives your Frost Ward a ",["$","$L22","2",{"tree":2,"talent":0,"values":["10","20"]}],"% chance to reflect Frost spells and effects while active."],
        spellIds: {"rank1":11189,"rank2":28332},
      },
      {
        id: 1,
        name: "Improved Frostbolt",
        icon: "spell_frost_frostbolt02",
        ranks: 5,
        row: 1,
        col: 2,
        description: ["Improved FrostboltInstantReduces the casting time of your Frostbolt spell by ",["$","$L22","1",{"tree":2,"talent":1,"values":["200","300","400","500"]}]," sec."],
        spellIds: {"rank1":11070,"rank2":12473,"rank3":16763,"rank4":16765,"rank5":16766},
      },
      {
        id: 2,
        name: "Elemental Precision",
        icon: "spell_ice_magicdamage",
        ranks: 3,
        row: 1,
        col: 3,
        description: ["Elemental PrecisionInstantReduces the chance that the opponent can resist your Frost and Fire spells by ",["$","$L22","1",{"tree":2,"talent":2,"values":["2","4","6"]}],"%."],
        spellIds: {"rank1":29438,"rank2":29439,"rank3":29440},
      },
      {
        id: 4,
        name: "Piercing Ice",
        icon: "spell_frost_frostbolt",
        ranks: 3,
        row: 2,
        col: 1,
        description: ["Piercing IceInstantIncreases the damage done by your Frost spells by ",["$","$L22","1",{"tree":2,"talent":4,"values":["2","4","6"]}],"%."],
        spellIds: {"rank1":11151,"rank2":12952,"rank3":12953},
      },
      {
        id: 5,
        name: "Frostbite",
        icon: "spell_frost_frostarmor",
        ranks: 3,
        row: 2,
        col: 2,
        description: ["FrostbiteInstantGives your Chill effects a ",["$","$L22","1",{"tree":2,"talent":5,"values":["5","10","15"]}],"% chance to freeze the target for 5 sec."],
        spellIds: {"rank1":11071,"rank2":12496,"rank3":12497},
      },
      {
        id: 6,
        name: "Improved Frost Nova",
        icon: "spell_frost_freezingbreath",
        ranks: 2,
        row: 2,
        col: 3,
        description: ["Improved Frost NovaInstantReduces the cooldown of your Frost Nova spell by ",["$","$L22","1",{"tree":2,"talent":6,"values":["2000","4000"]}]," sec."],
        spellIds: {"rank1":11165,"rank2":12475},
      },
      {
        id: 7,
        name: "Permafrost",
        icon: "spell_frost_wisp",
        ranks: 3,
        row: 2,
        col: 4,
        description: ["PermafrostInstantIncreases the duration of your Chill effects by ",["$","$L22","1",{"tree":2,"talent":7,"values":["1000","2000","3000"]}]," secs and reduces the target's speed by an additional ",["$","$L22","2",{"tree":2,"talent":7,"values":["4","7","10"]}],"%."],
        spellIds: {"rank1":11175,"rank2":12569,"rank3":12571},
      },
      {
        id: 8,
        name: "Ice Shards",
        icon: "spell_frost_iceshard",
        ranks: 5,
        row: 3,
        col: 1,
        description: ["Ice ShardsInstantIncreases the critical strike damage bonus of your Frost spells by ",["$","$L22","1",{"tree":2,"talent":8,"values":["20","60","80","100"]}],"%."],
        spellIds: {"rank1":11207,"rank2":12672,"rank3":15047,"rank4":15052,"rank5":15053},
      },
      {
        id: 9,
        name: "Cold Snap",
        icon: "spell_frost_wizardmark",
        ranks: 1,
        row: 3,
        col: 2,
        description: "Cold SnapInstant600 sec cooldownWhen activated, this spell finishes the cooldown on all of your Frost spells.",
        spellIds: {"rank1":12472},
      },
      {
        id: 11,
        name: "Improved Blizzard",
        icon: "spell_frost_icestorm",
        ranks: 3,
        row: 3,
        col: 4,
        description: ["Improved BlizzardInstantAdds a chill effect to your Blizzard spell. This effect lowers the target's movement speed by ",["$","$L22","1",{"tree":2,"talent":11,"values":["20","30","40"]}],"%. Lasts 2 sec."],
        spellIds: {"rank1":11185,"rank2":12487,"rank3":12488},
      },
      {
        id: 12,
        name: "Arctic Reach",
        icon: "spell_shadow_darkritual",
        ranks: 2,
        row: 4,
        col: 1,
        description: ["Arctic ReachInstantIncreases the range of your Frostbolt, Icicles and Blizzard spells and the radius of your Frost Nova and Cone of Cold spells by ",["$","$L22","1",{"tree":2,"talent":12,"values":["10","20"]}],"%."],
        spellIds: {"rank1":16757,"rank2":16758},
      },
      {
        id: 13,
        name: "Frost Channeling",
        icon: "spell_frost_stun",
        ranks: 3,
        row: 4,
        col: 2,
        description: ["Frost ChannelingInstantReduces the mana cost of your Frost spells by ",["$","$L22","1",{"tree":2,"talent":13,"values":["5","10","15"]}],"% and reduces the threat caused by your Frost spells by ",["$","$L22","2",{"tree":2,"talent":13,"values":["10","20","30"]}],"%."],
        spellIds: {"rank1":11160,"rank2":12518,"rank3":12519},
      },
      {
        id: 14,
        name: "Shatter",
        icon: "spell_frost_frostshock",
        ranks: 5,
        row: 4,
        col: 3,
        description: ["ShatterInstantIncreases the critical strike chance of all your spells against frozen targets by ",["$","$L22","1",{"tree":2,"talent":14,"values":["7","14","21","28","35"]}],"%."],
        spellIds: {"rank1":11170,"rank2":12982,"rank3":12983,"rank4":12984,"rank5":12985},
        requires: 6,
        reqRanks: 2,
      },
      {
        id: 17,
        name: "Ice Block",
        icon: "spell_frost_frost",
        ranks: 1,
        row: 5,
        col: 2,
        description: "Ice Block15 manaInstantYou become encased in a block of ice, protecting you from all physical attacks and spells for 10 sec, but during that time you cannot attack, move or cast spells.",
        spellIds: {"rank1":11958},
      },
      {
        id: 18,
        name: "Icicles",
        icon: "spell_frost_frostblast",
        ranks: 1,
        row: 5,
        col: 3,
        description: "Icicles mana30 yd rangeChanneledDraw upon frost leylines, becoming frozen in place, and launch icicles at the enemy, dealing 101 Frost damage every 1 sec for 5 sec. Damage taken has a high chance to shatter your icy prison, dealing 30% of your base health as Frost damage to you. Cancelling the effect early will not remove the freeze effect.",
        spellIds: {"rank1":52516},
      },
      {
        id: 19,
        name: "Improved Cone of Cold",
        icon: "spell_frost_glacier",
        ranks: 3,
        row: 5,
        col: 4,
        description: ["Improved Cone of ColdInstantIncreases the damage dealt by your Cone of Cold spell by ",["$","$L22","1",{"tree":2,"talent":19,"values":["15","25","35"]}],"%."],
        spellIds: {"rank1":11190,"rank2":12489,"rank3":12490},
      },
      {
        id: 20,
        name: "Winter's Chill",
        icon: "spell_frost_chillingblast",
        ranks: 5,
        row: 6,
        col: 1,
        description: ["Winter's ChillInstantGives your Frost damage spells a ",["$","$L22","1",{"tree":2,"talent":20,"values":["20","40","60","80","100"]}],"% chance to apply the Winter's Chill effect, which increases the chance a Frost spell will critically hit the target by 2% for 15 sec. Stacks up to 15001 times."],
        spellIds: {"rank1":11180,"rank2":28592,"rank3":28593,"rank4":28594,"rank5":28595},
      },
      {
        id: 22,
        name: "Flash Freeze",
        icon: "spell_fire_frostresistancetotem",
        ranks: 2,
        row: 6,
        col: 3,
        description: ["Flash FreezeInstantIf an effect that causes a target to freeze is not applied due to the target being permanently immune to freeze effects, you have a ",["$","$L22","1",{"tree":2,"talent":22,"values":["50","100"]}],"% chance to gain Flash Freeze instead. Flash Freeze resets the cooldown of Icicles and reduces the duration and the time between each Icicle by 80% for your next Icicles."],
        spellIds: {"rank1":51999,"rank2":52501},
        requires: 18,
        reqRanks: 1,
      },
      {
        id: 25,
        name: "Ice Barrier",
        icon: "spell_ice_lament",
        ranks: 1,
        row: 7,
        col: 2,
        description: "Ice Barrier manaInstantInstantly shields you, absorbing 438 damage and increasing your Frost damage by 15%. Lasts 60 sec. While the shield holds, spells will not be interrupted.",
        spellIds: {"rank1":11426},
        requires: 17,
        reqRanks: 1,
      }
    ]
  }
};
