// Rogue talents for Turtle WoW
export const rogueTalents = {
  assassination: {
    name: "Assassination",
    icon: "ability_rogue_eviscerate",
    talents: [
      {
        id: 0,
        name: "Improved Eviscerate",
        icon: "ability_rogue_eviscerate",
        ranks: 3,
        row: 1,
        col: 1,
        description: ["Improved EviscerateInstantIncreases the damage done by your Eviscerate ability by ",["$","$L22","1",{"tree":0,"talent":0,"values":["5","10","15"]}],"%."],
        spellIds: {"rank1":14162,"rank2":14163,"rank3":14164},
      },
      {
        id: 1,
        name: "Remorseless Attacks",
        icon: "ability_fiegndead",
        ranks: 2,
        row: 1,
        col: 2,
        description: ["Remorseless AttacksInstantAfter killing an opponent that yields experience or honor, gives you a ",["$","$L22","1",{"tree":0,"talent":1,"values":["20","40"]}],"% increased critical strike chance on your next Combo Point generating ability. Lasts 40 sec."],
        spellIds: {"rank1":14144,"rank2":14148},
      },
      {
        id: 2,
        name: "Malice",
        icon: "ability_racial_bloodrage",
        ranks: 5,
        row: 1,
        col: 3,
        description: ["MaliceInstantIncreases your critical strike chance by ",["$","$L22","1",{"tree":0,"talent":2,"values":["1","2","3","4","5"]}],"%."],
        spellIds: {"rank1":14138,"rank2":14139,"rank3":14140,"rank4":14141,"rank5":14142},
      },
      {
        id: 4,
        name: "Ruthlessness",
        icon: "ability_druid_disembowel",
        ranks: 3,
        row: 2,
        col: 1,
        description: ["RuthlessnessInstantGives your finishing moves a ",["$","$L22","1",{"tree":0,"talent":4,"values":["33","66","100"]}],"% chance to add a combo point to your target."],
        spellIds: {"rank1":14156,"rank2":14160,"rank3":14161},
      },
      {
        id: 5,
        name: "Murder",
        icon: "spell_shadow_deathscream",
        ranks: 2,
        row: 2,
        col: 2,
        description: ["MurderInstantIncreases all damage caused against Humanoid, Giant, Beast and Dragonkin targets by ",["$","$L22","1",{"tree":0,"talent":5,"values":["1","2"]}],"%."],
        spellIds: {"rank1":14158,"rank2":14159},
      },
      {
        id: 7,
        name: "Improved Blade Tactics",
        icon: "ability_rogue_slicedice",
        ranks: 3,
        row: 2,
        col: 4,
        description: ["Improved Blade TacticsInstantIncreases the duration of your Slice and Dice and Flourish abilities by ",["$","$L22","1",{"tree":0,"talent":7,"values":["15","30","45"]}],"%."],
        spellIds: {"rank1":14165,"rank2":14166,"rank3":14167},
      },
      {
        id: 8,
        name: "Relentless Strikes",
        icon: "ability_warrior_decisivestrike",
        ranks: 1,
        row: 3,
        col: 1,
        description: "Relentless StrikesInstantYour finishing moves have a 20% chance per combo point to restore 20 energy and increase the damage of your finishing moves by 5% for 30 sec. Stacks up to 30001 times.",
        spellIds: {"rank1":14179},
      },
      {
        id: 9,
        name: "Throwing Weapon Specialization",
        icon: "inv_throwingknife_01",
        ranks: 2,
        row: 3,
        col: 2,
        description: ["Throwing Weapon SpecializationInstantIncreases the range of Throw and Deadly Throw by ",["$","$L22","1",{"tree":0,"talent":9,"values":["3","6"]}]," yards and gives your Deadly Throw a ",["$","$L22","2",{"tree":0,"talent":9,"values":["50","100"]}],"% chance to apply your off-hand weapon poison."],
        spellIds: {"rank1":13710,"rank2":13859},
      },
      {
        id: 10,
        name: "Lethality",
        icon: "ability_criticalstrike",
        ranks: 5,
        row: 3,
        col: 3,
        description: ["LethalityInstantIncreases the critical strike damage bonus of your combo point generating abilities by ",["$","$L22","1",{"tree":0,"talent":10,"values":["6","12","18","24","30"]}],"%."],
        spellIds: {"rank1":14128,"rank2":14132,"rank3":14135,"rank4":14136,"rank5":14137},
        requires: 2,
        reqRanks: 5,
      },
      {
        id: 12,
        name: "Taste for Blood",
        icon: "inv_misc_bone_09",
        ranks: 2,
        row: 4,
        col: 1,
        description: ["Taste for BloodInstantIncreases the duration of your Rupture by ",["$","$L22","1",{"tree":0,"talent":12,"values":["4000","6000"]}]," sec. Each time you use Rupture, your physical damage is increased by ",["$","$L22","2",{"tree":0,"talent":12,"values":["1","2"]}],"% per combo point for its full duration, regardless of successful application."],
        spellIds: {"rank1":14174,"rank2":14175},
      },
      {
        id: 13,
        name: "Vile Poisons",
        icon: "ability_rogue_feigndeath",
        ranks: 3,
        row: 4,
        col: 2,
        description: ["Vile PoisonsInstantIncreases the damage dealt by your poisons by ",["$","$L22","1",{"tree":0,"talent":13,"values":["10","20","30"]}],"% and gives your poisons an additional ",["$","$L22","2",{"tree":0,"talent":13,"values":["14","27","40"]}],"% chance to resist dispel effects. Corrosive Poison and Dissolvent Poison only apply to Elementals, Mechanicals, Giants and Undead."],
        spellIds: {"rank1":16513,"rank2":16514,"rank3":16515},
      },
      {
        id: 14,
        name: "Improved Poisons",
        icon: "ability_poisons",
        ranks: 3,
        row: 4,
        col: 3,
        description: ["Improved PoisonsInstantIncreases the chance to apply poisons to your target by ",["$","$L22","1",{"tree":0,"talent":14,"values":["3","6","10"]}],"%."],
        spellIds: {"rank1":14113,"rank2":14114,"rank3":14115},
      },
      {
        id: 16,
        name: "Efficient Poisons",
        icon: "ability_creature_poison_06",
        ranks: 3,
        row: 5,
        col: 1,
        description: ["Efficient PoisonsInstantReduces the chance your poisons will be resisted by ",["$","$L22","1",{"tree":0,"talent":16,"values":["4","8","12"]}],"% and gives your poison applications a ",["$","$L22","2",{"tree":0,"talent":16,"values":["15","30","45"]}],"% chance to not consume a charge."],
        spellIds: {"rank1":52518,"rank2":52519,"rank3":52520},
      },
      {
        id: 17,
        name: "Envenom",
        icon: "inv_sword_31",
        ranks: 1,
        row: 5,
        col: 2,
        description: "Envenom20 mana100 yd rangeInstantFinishing move that increases the effectiveness and the chance to apply poisons to your target by 30%. Lasts longer per combo point:\n 1 point : 12 seconds\n 2 points: 16 seconds\n 3 points: 20 seconds\n 4 points: 24 seconds\n 5 points: 28 seconds",
        spellIds: {"rank1":52531},
      },
      {
        id: 18,
        name: "Cold Blood",
        icon: "spell_ice_lament",
        ranks: 1,
        row: 5,
        col: 3,
        description: "Cold BloodInstant180 sec cooldownWhen activated, increases the critical strike chance of your next Sinister Strike, Backstab, Ambush, Noxious Assault, or Eviscerate by 100%.",
        spellIds: {"rank1":14177},
      },
      {
        id: 20,
        name: "Vigor",
        icon: "spell_nature_earthbindtotem",
        ranks: 2,
        row: 6,
        col: 1,
        description: ["VigorInstantIncreases your maximum Energy by ",["$","$L22","1",{"tree":0,"talent":20,"values":["5.","10."]}]," Each time you apply poison to your target, you have a ",["$","$L22","2",{"tree":0,"talent":20,"values":["50","100"]}],"% chance to gain 2 Energy."],
        spellIds: {"rank1":14983,"rank2":52527},
      },
      {
        id: 22,
        name: "Seal Fate",
        icon: "spell_shadow_chilltouch",
        ranks: 5,
        row: 6,
        col: 3,
        description: ["Seal FateInstantYour critical strikes from abilities that add combo points have a ",["$","$L22","1",{"tree":0,"talent":22,"values":["20","40","60","80","100"]}],"% chance to add an additional combo point."],
        spellIds: {"rank1":14186,"rank2":14190,"rank3":14193,"rank4":14194,"rank5":14195},
      },
      {
        id: 25,
        name: "Noxious Assault",
        icon: "spell_double_dose_3",
        ranks: 1,
        row: 7,
        col: 2,
        description: "Noxious Assault mana5 yd rangeInstantStrikes with both weapons, dealing 30 damage plus 35% of your Attack Power and applies poisons from both weapons. Awards 1 combo point.",
        spellIds: {"rank1":52714},
        requires: 17,
        reqRanks: 1,
      }
    ]
  },
  combat: {
    name: "Combat",
    icon: "ability_warrior_warcry",
    talents: [
      {
        id: 1,
        name: "Opportunity",
        icon: "ability_warrior_warcry",
        ranks: 5,
        row: 1,
        col: 2,
        description: ["OpportunityInstantIncreases the damage dealt when striking from behind with your Backstab, Garrote, or Ambush abilities by ",["$","$L22","1",{"tree":1,"talent":1,"values":["4","8","12","16","20"]}],"%."],
        spellIds: {"rank1":14057,"rank2":14072,"rank3":14073,"rank4":14074,"rank5":14075},
      },
      {
        id: 2,
        name: "Lightning Reflexes",
        icon: "spell_nature_invisibilty",
        ranks: 5,
        row: 1,
        col: 3,
        description: ["Lightning ReflexesInstantIncreases your Dodge chance by ",["$","$L22","1",{"tree":1,"talent":2,"values":["1","2","3","4","5"]}],"%."],
        spellIds: {"rank1":13712,"rank2":13788,"rank3":13789,"rank4":13790,"rank5":13791},
      },
      {
        id: 4,
        name: "Deflection",
        icon: "ability_parry",
        ranks: 5,
        row: 2,
        col: 1,
        description: ["DeflectionInstantIncreases your Parry chance by ",["$","$L22","1",{"tree":1,"talent":4,"values":["1","2","3","4","5"]}],"%."],
        spellIds: {"rank1":13713,"rank2":13853,"rank3":13854,"rank4":13855,"rank5":13856},
      },
      {
        id: 5,
        name: "Improved Backstab",
        icon: "ability_backstab",
        ranks: 3,
        row: 2,
        col: 2,
        description: ["Improved BackstabInstantIncreases the critical strike chance of your Backstab ability by ",["$","$L22","1",{"tree":1,"talent":5,"values":["10","20","30"]}],"% and gives your Backstab a ",["$","$L22","2",{"tree":1,"talent":5,"values":["15","30","45"]}],"% chance to award an additional combo point."],
        spellIds: {"rank1":13733,"rank2":13865,"rank3":13866},
      },
      {
        id: 6,
        name: "Precision",
        icon: "ability_marksmanship",
        ranks: 5,
        row: 2,
        col: 3,
        description: ["PrecisionInstantIncreases your chance to hit with melee weapons by ",["$","$L22","1",{"tree":1,"talent":6,"values":["1","2","3","4","5"]}],"%."],
        spellIds: {"rank1":13705,"rank2":13832,"rank3":13843,"rank4":13844,"rank5":13845},
      },
      {
        id: 8,
        name: "Riposte",
        icon: "ability_warrior_challange",
        ranks: 1,
        row: 3,
        col: 1,
        description: "Riposte10 mana5 yd rangeInstant6 sec cooldownA strike that becomes active after parrying an opponent's attack. This attack deals 150% weapon damage and disarms the target for 6 sec.",
        spellIds: {"rank1":14251},
        requires: 4,
        reqRanks: 5,
      },
      {
        id: 9,
        name: "Improved Sprint",
        icon: "ability_rogue_sprint",
        ranks: 2,
        row: 3,
        col: 2,
        description: ["Improved SprintInstantGives a ",["$","$L22","1",{"tree":1,"talent":9,"values":["50","100"]}],"% chance to remove all movement impairing effects when you activate your Sprint ability."],
        spellIds: {"rank1":13743,"rank2":13875},
      },
      {
        id: 11,
        name: "Setup",
        icon: "spell_nature_mirrorimage",
        ranks: 3,
        row: 3,
        col: 4,
        description: ["SetupInstantGives you a ",["$","$L22","1",{"tree":1,"talent":11,"values":["15","30","45"]}],"% chance to add a combo point to your target after dodging their attack or fully resisting one of their spells."],
        spellIds: {"rank1":13983,"rank2":14070,"rank3":14071},
      },
      {
        id: 12,
        name: "Improved Kick",
        icon: "ability_kick",
        ranks: 2,
        row: 4,
        col: 1,
        description: ["Improved KickInstantGives your Kick ability a ",["$","$L22","1",{"tree":1,"talent":12,"values":["50","100"]}],"% chance to silence the target for 2 sec."],
        spellIds: {"rank1":13754,"rank2":13867},
      },
      {
        id: 13,
        name: "Concussive Blows",
        icon: "inv_mace_01",
        ranks: 5,
        row: 4,
        col: 2,
        description: ["Concussive BlowsInstantGives you a ",["$","$L22","1",{"tree":1,"talent":13,"values":["1","2","3","4","6"]}],"% chance to stun your target for 3 sec with a mace."],
        spellIds: {"rank1":13709,"rank2":13800,"rank3":13801,"rank4":13802,"rank5":13803},
      },
      {
        id: 14,
        name: "Dual Wield Specialization",
        icon: "ability_dualwield",
        ranks: 5,
        row: 4,
        col: 3,
        description: ["Dual Wield SpecializationInstantIncreases the damage done by your offhand weapon by ",["$","$L22","1",{"tree":1,"talent":14,"values":["10","20","30","40","50"]}],"%."],
        spellIds: {"rank1":13715,"rank2":13848,"rank3":13849,"rank4":13851,"rank5":13852},
        requires: 6,
        reqRanks: 5,
      },
      {
        id: 16,
        name: "Close Quarters Combat",
        icon: "inv_weapon_shortblade_05",
        ranks: 2,
        row: 5,
        col: 1,
        description: ["Close Quarters CombatInstantIncreases your chance to get a critical strike with Maces, Daggers and Fist Weapons by ",["$","$L22","1",{"tree":1,"talent":16,"values":["2","5"]}],"%."],
        spellIds: {"rank1":13706,"rank2":13804},
      },
      {
        id: 17,
        name: "Surprise Attack",
        icon: "ability_rogue_surpriseattack",
        ranks: 1,
        row: 5,
        col: 2,
        description: "Surprise Attack10 mana5 yd rangeInstantA surprise strike that deals 25% of your Attack Power as damage.\nOnly useable after the target dodges and cannot be blocked, dodged or parried by the target. Awards 1 combo point.",
        spellIds: {"rank1":52511},
      },
      {
        id: 18,
        name: "Hack and Slash",
        icon: "inv_sword_27",
        ranks: 2,
        row: 5,
        col: 3,
        description: "Hack and SlashInstantGives you a 5% chance to get an extra attack on the same target after dealing damage with your Axe or Sword.",
        spellIds: {"rank1":13960,"rank2":13961},
      },
      {
        id: 19,
        name: "Weapon Expertise",
        icon: "spell_holy_blessingofstrength",
        ranks: 2,
        row: 5,
        col: 4,
        description: ["Weapon ExpertiseInstantIncreases your skill with Axe, Dagger, Fist, Mace and Sword weapons by ",["$","$L22","1",{"tree":1,"talent":19,"values":["3.","5."]}]],
        spellIds: {"rank1":30919,"rank2":30920},
      },
      {
        id: 21,
        name: "Blade Rush",
        icon: "ability_warrior_weaponmastery",
        ranks: 2,
        row: 6,
        col: 2,
        description: ["Blade RushInstantIncreases your melee attack speed by ",["$","$L22","1",{"tree":1,"talent":21,"values":["2","5"]}],"% and reduces the time between your Energy regeneration ticks by an amount equal to your Agility."],
        spellIds: {"rank1":52507,"rank2":52508},
        requires: 17,
        reqRanks: 1,
      },
      {
        id: 22,
        name: "Aggression",
        icon: "ability_racial_avatar",
        ranks: 3,
        row: 6,
        col: 3,
        description: ["AggressionInstantIncreases the damage of your Sinister Strike, Eviscerate, Riposte and Surprise Attack abilities by ",["$","$L22","1",{"tree":1,"talent":22,"values":["3","6","10"]}],"%."],
        spellIds: {"rank1":18427,"rank2":18428,"rank3":18429},
      },
      {
        id: 25,
        name: "Adrenaline Rush",
        icon: "spell_shadow_shadowworddominate",
        ranks: 1,
        row: 7,
        col: 2,
        description: "Adrenaline RushInstant180 sec cooldownIncreases your Energy regeneration rate by 100% for 15 sec.",
        spellIds: {"rank1":13750},
      }
    ]
  },
  subtlety: {
    name: "Subtlety",
    icon: "ability_stealth",
    talents: [
      {
        id: 1,
        name: "Camouflage",
        icon: "ability_stealth",
        ranks: 5,
        row: 1,
        col: 2,
        description: ["CamouflageInstantIncreases your speed while stealthed by ",["$","$L22","1",{"tree":2,"talent":1,"values":["3","6","9","12","15"]}],"% and reduces the cooldown of your Stealth ability by ",["$","$L22","2",{"tree":2,"talent":1,"values":["1000","2000","3000","4000","5000"]}]," sec. In addition, reduces the chance enemies have to detect you while in Stealth mode."],
        spellIds: {"rank1":13975,"rank2":14062,"rank3":14063,"rank4":14064,"rank5":14065},
      },
      {
        id: 2,
        name: "Improved Expose Armor",
        icon: "ability_warrior_riposte",
        ranks: 2,
        row: 1,
        col: 3,
        description: ["Improved Expose ArmorInstantIncreases the armor reduced by your Expose Armor ability by ",["$","$L22","1",{"tree":2,"talent":2,"values":["25","50"]}],"%."],
        spellIds: {"rank1":14168,"rank2":14169},
      },
      {
        id: 3,
        name: "Improved Gouge",
        icon: "ability_gouge",
        ranks: 3,
        row: 1,
        col: 4,
        description: ["Improved GougeInstantIncreases the effect duration of your Gouge ability by ",["$","$L22","1",{"tree":2,"talent":3,"values":["500","1000","1500"]}]," sec."],
        spellIds: {"rank1":13741,"rank2":13793,"rank3":13792},
      },
      {
        id: 4,
        name: "Improved Ambush",
        icon: "ability_rogue_ambush",
        ranks: 3,
        row: 2,
        col: 1,
        description: ["Improved AmbushInstantIncreases the critical strike chance of your Ambush ability by ",["$","$L22","1",{"tree":2,"talent":4,"values":["15","30","45"]}],"%. Your Ambush will refund ",["$","$L22","2",{"tree":2,"talent":4,"values":["5","10","15"]}]," Energy if it does not result in a critical strike."],
        spellIds: {"rank1":14079,"rank2":14080,"rank3":14081},
      },
      {
        id: 5,
        name: "Elusiveness",
        icon: "spell_magic_lesserinvisibilty",
        ranks: 2,
        row: 2,
        col: 2,
        description: ["ElusivenessInstantReduces the cooldown of your Vanish and Blind abilities by ",["$","$L22","1",{"tree":2,"talent":5,"values":["45000","90000"]}]," sec."],
        spellIds: {"rank1":13981,"rank2":14066},
      },
      {
        id: 6,
        name: "Serrated Blades",
        icon: "inv_sword_17",
        ranks: 3,
        row: 2,
        col: 3,
        description: ["Serrated BladesInstantCauses your attacks to ignore ",["$","$L22","1",{"tree":2,"talent":6,"values":["1.67","3.34","5"]}]," of your target's Armor per level and increases the damage dealt by your Rupture and Garrote abilities by ",["$","$L22","2",{"tree":2,"talent":6,"values":["10","20","30"]}],"%."],
        spellIds: {"rank1":14171,"rank2":14172,"rank3":14173},
      },
      {
        id: 8,
        name: "Initiative",
        icon: "spell_shadow_fumble",
        ranks: 3,
        row: 3,
        col: 1,
        description: ["InitiativeInstantGives you a ",["$","$L22","1",{"tree":2,"talent":8,"values":["33","66","100"]}],"% chance to add an additional combo point to your target when using your Ambush, Garrote, or Cheap Shot ability."],
        spellIds: {"rank1":13976,"rank2":13979,"rank3":13980},
      },
      {
        id: 9,
        name: "Improved Ghostly Strike",
        icon: "inv_sword_02",
        ranks: 3,
        row: 3,
        col: 2,
        description: ["Improved Ghostly StrikeInstantYour Ghostly Strike increases your movement speed by ",["$","$L22","1",{"tree":2,"talent":9,"values":["5","10","15"]}],"% and increases your party members' movement speed by ",["$","$L22","2",{"tree":2,"talent":9,"values":["2","4","6"]}],"% within 0 yards for 5 sec. In addition, reduces the Energy cost of your Ghostly Strike by ",["$","$L22","3",{"tree":2,"talent":9,"values":["3.","6.","10."]}]],
        spellIds: {"rank1":51970,"rank2":51971,"rank3":51972},
      },
      {
        id: 10,
        name: "Smoke Bomb",
        icon: "spell_smoke_bomb_5",
        ranks: 1,
        row: 3,
        col: 3,
        description: "Creates a cloud of thick smoke in 8 yards around you for 8 sec. All targets inside the smoke have a 20% reduced chance of being hit by attacks and spells for the duration.",
        spellIds: {"rank1":51969},
      },
      {
        id: 11,
        name: "Hemorrhage",
        icon: "spell_shadow_lifedrain",
        ranks: 1,
        row: 3,
        col: 4,
        description: "Hemorrhage40 mana5 yd rangeInstantAn instant strike that deals 110% weapon damage and causes the target to hemorrhage, increasing any Physical damage dealt to the target by 2%. Lasts 50 charges or 15 sec. Awards 1 combo point.",
        spellIds: {"rank1":16511},
      },
      {
        id: 12,
        name: "Cloaked in Shadows",
        icon: "spell_cloaked_in_shadows_2",
        ranks: 2,
        row: 4,
        col: 1,
        description: ["Cloaked in ShadowsInstantWhenever you Vanish, you and nearby party members within 20 yards are cloaked in shadows, gaining a barrier that absorbs up to ",["$","$L22","1",{"tree":2,"talent":12,"values":["6","12"]}],"% of your maximum health for 20 sec."],
        spellIds: {"rank1":52707,"rank2":52709},
      },
      {
        id: 13,
        name: "Blackjack",
        icon: "ability_sap",
        ranks: 2,
        row: 4,
        col: 2,
        description: ["BlackjackInstantYour Sap and Blind abilities reduce the target's damage dealt by ",["$","$L22","1",{"tree":2,"talent":13,"values":["5","10"]}],"% for 8 sec when their effect ends or fails to apply. In addition, you have a ",["$","$L22","2",{"tree":2,"talent":13,"values":["50","100"]}],"% chance to return to stealth after using your Sap ability."],
        spellIds: {"rank1":14076,"rank2":14094},
      },
      {
        id: 14,
        name: "Blinding Haze",
        icon: "ability_rogue_shadowstep",
        ranks: 3,
        row: 4,
        col: 3,
        description: ["Blinding HazeInstantReduces the Energy cost of your Distract by ",["$","$L22","1",{"tree":2,"talent":14,"values":["5.","10.","15."]}]," In addition, targets hit by your Distract have their chance to hit reduced by ",["$","$L22","2",{"tree":2,"talent":14,"values":["2","4","6"]}],"% for 6 sec. This effect is guaranteed to be applied."],
        spellIds: {"rank1":51680,"rank2":51681,"rank3":51682},
      },
      {
        id: 16,
        name: "Dirty Deeds",
        icon: "spell_shadow_summonsuccubus",
        ranks: 2,
        row: 5,
        col: 1,
        description: ["Dirty DeedsInstantReduces the Energy cost of your Cheap Shot and Garrote abilities by ",["$","$L22","1",{"tree":2,"talent":16,"values":["10.","20."]}]],
        spellIds: {"rank1":14082,"rank2":14083},
      },
      {
        id: 17,
        name: "Preparation",
        icon: "spell_shadow_antishadow",
        ranks: 1,
        row: 5,
        col: 2,
        description: "PreparationInstant420 sec cooldownWhen activated, this ability immediately finishes the cooldown on your other Rogue abilities.",
        spellIds: {"rank1":14185},
      },
      {
        id: 18,
        name: "Shadow of Death",
        icon: "spell_shadow_of_death_3b",
        ranks: 1,
        row: 5,
        col: 3,
        description: "Shadow of Death30 mana5 yd rangeInstant60 sec cooldownA finishing move that etches a sigil onto the target for 6 sec. The sigil accumulates damage equal to a percentage of all damage the target takes during its duration, up to a percentage of your Attack Power. When the maximum capacity is reached or the sigil expires, the stored damage is unleashed as Physical damage. Both values increase with each combo point:\n 1 point : 10% of damage accumulated, up to 50% of Attack Power\n 2 points: 20% of damage accumulated, up to 100% of Attack Power\n 3 points: 30% of damage accumulated, up to 150% of Attack Power\n 4 points: 40% of damage accumulated, up to 200% of Attack Power\n 5 points: 50% of damage accumulated, up to 250% of Attack Power",
        spellIds: {"rank1":52710},
      },
      {
        id: 19,
        name: "Bloody Mess",
        icon: "spell_shadow_bloodboil",
        ranks: 2,
        row: 5,
        col: 4,
        description: "Bloody MessInstantReduces the Energy cost of your Hemorrhage by 5 and increases the Physical damage dealt bonus of your Hemorrhage by 100%.",
        spellIds: {"rank1":51974,"rank2":51975},
        requires: 11,
        reqRanks: 1,
      },
      {
        id: 20,
        name: "Honor Among Thieves",
        icon: "inv_throwingknife_05",
        ranks: 2,
        row: 6,
        col: 1,
        description: ["Honor Among ThievesInstantPhysical critical strikes by you or party members within 20 yards grant you ",["$","$L22","1",{"tree":2,"talent":20,"values":["2","5"]}]," Energy."],
        spellIds: {"rank1":52512,"rank2":52514},
      },
      {
        id: 22,
        name: "Tricks of the Trade",
        icon: "inv_misc_key_03",
        ranks: 5,
        row: 6,
        col: 3,
        description: ["Tricks of the TradeInstantYour opening moves have a ",["$","$L22","1",{"tree":2,"talent":22,"values":["20","40","60","80","100"]}],"% chance and your finishing moves have a ",["$","$L22","2",{"tree":2,"talent":22,"values":["4","8","12","16","20"]}],"% chance per combo point to increase your party members' critical strike chance by 2% for 12 sec. This effect stacks up to 12001 times."],
        spellIds: {"rank1":52541,"rank2":52542,"rank3":52543,"rank4":52544,"rank5":52545},
      },
      {
        id: 25,
        name: "Mark for Death",
        icon: "ability_creature_cursed_02",
        ranks: 1,
        row: 7,
        col: 2,
        description: "Mark for Death40 mana5 yd rangeInstant180 sec cooldownA marking strike that deals 135% weapon damage and reveals the targetâ€™s vulnerabilities, increasing your party members' Attack Power by 30% and damage done by magical spells and effects up to 18% of your melee Attack Power for 8 sec. Cannot be blocked, dodged or parried by the target. Awards 2 combo points.",
        spellIds: {"rank1":52538},
        requires: 17,
        reqRanks: 1,
      }
    ]
  }
};
