// Warlock talents for Turtle WoW
export const warlockTalents = {
  affliction: {
    name: "Affliction",
    icon: "spell_shadow_unsummonbuilding",
    talents: [
      {
        id: 1,
        name: "Suppression",
        icon: "spell_shadow_unsummonbuilding",
        ranks: 5,
        row: 1,
        col: 2,
        description: ["SuppressionInstantReduces the chance for enemies to resist your Affliction spells by ",["$","$L22","1",{"tree":0,"talent":1,"values":["2","4","6","8","10"]}],"%."],
        spellIds: {"rank1":18174, "rank2":18175, "rank3":18176, "rank4":18177, "rank5":18178},
      },
      {
        id: 2,
        name: "Improved Corruption",
        icon: "spell_shadow_abominationexplosion",
        ranks: 5,
        row: 1,
        col: 3,
        description: ["Improved CorruptionInstantReduces the casting time of your Corruption spell by ",["$","$L22","1",{"tree":0,"talent":2,"values":["300","600","900","1200","1500"]}]," sec."],
        spellIds: {"rank1":17810, "rank2":17811, "rank3":17812, "rank4":17813, "rank5":17814},
      },
      {
        id: 4,
        name: "Improved Curse of Weakness",
        icon: "spell_shadow_curseofmannoroth",
        ranks: 2,
        row: 2,
        col: 1,
        description: ["Improved Curse of WeaknessInstantIncreases the attack speed reduction of your Curse of Weakness by ",["$","$L22","1",{"tree":0,"talent":4,"values":["3","5"]}],"%."],
        spellIds: {"rank1":18179, "rank2":18180},
      },
      {
        id: 5,
        name: "Resilient Shadows",
        icon: "spell_shadow_soulleech_1",
        ranks: 3,
        row: 2,
        col: 2,
        description: ["Resilient ShadowsInstantReduces the chance your Affliction spells will be dispelled by an additional ",["$","$L22","1",{"tree":0,"talent":5,"values":["5","10","15"]}],"%."],
        spellIds: {"rank1":52547, "rank2":52548, "rank3":52549},
      },
      {
        id: 6,
        name: "Improved Life Tap",
        icon: "spell_shadow_burningspirit",
        ranks: 2,
        row: 2,
        col: 3,
        description: ["Improved Life TapInstantIncreases the amount of Mana awarded by your Life Tap spell by ",["$","$L22","1",{"tree":0,"talent":6,"values":["10","20"]}],"%."],
        spellIds: {"rank1":18182, "rank2":18183},
      },
      {
        id: 7,
        name: "Improved Drains",
        icon: "spell_shadow_lifedrain02",
        ranks: 2,
        row: 2,
        col: 4,
        description: ["Improved DrainsInstantIncreases the effectiveness of your Drain Soul, Drain Life and Drain Mana by ",["$","$L22","1",{"tree":0,"talent":7,"values":["5","10"]}],"%."],
        spellIds: {"rank1":45913, "rank2":45914},
      },
      {
        id: 8,
        name: "Improved Curse of Agony",
        icon: "spell_shadow_curseofsargeras",
        ranks: 3,
        row: 3,
        col: 1,
        description: ["Improved Curse of AgonyInstantIncreases the damage done by your Curse of Agony by ",["$","$L22","1",{"tree":0,"talent":8,"values":["3","6","10"]}],"%."],
        spellIds: {"rank1":18827, "rank2":18829, "rank3":18830},
      },
      {
        id: 9,
        name: "Fel Concentration",
        icon: "spell_shadow_fingerofdeath",
        ranks: 2,
        row: 3,
        col: 2,
        description: ["Fel ConcentrationInstantGives your Affliction spells a ",["$","$L22","1",{"tree":0,"talent":9,"values":["35","70"]}],"% chance to not lose casting time when you take damage."],
        spellIds: {"rank1":17783, "rank2":17784},
      },
      {
        id: 10,
        name: "Curse of Exhaustion",
        icon: "spell_shadow_grimward",
        ranks: 1,
        row: 3,
        col: 3,
        description: "Curse of Exhaustion8% of base mana30 yd rangeInstantReduces the target's movement speed by 10% for 12 sec. Only one Curse per Warlock can be active on any one target.",
        spellIds: {"rank1":18223},
      },
      {
        id: 12,
        name: "Grim Reach",
        icon: "spell_shadow_callofbone",
        ranks: 2,
        row: 4,
        col: 1,
        description: ["Grim ReachInstantIncreases the range of your Affliction spells by ",["$","$L22","1",{"tree":0,"talent":12,"values":["10","20"]}],"%."],
        spellIds: {"rank1":18218, "rank2":18219},
      },
      {
        id: 13,
        name: "Nightfall",
        icon: "spell_shadow_twilight",
        ranks: 2,
        row: 4,
        col: 2,
        description: ["NightfallInstantGives your Corruption, Dark Harvest and Drain spells a ",["$","$L22","1",{"tree":0,"talent":13,"values":["2","4"]}],"% chance to cause you to enter a Shadow Trance state after damaging the opponent. The Shadow Trance state reduces the casting time of your next Shadow Bolt spell by 100% and makes it guaranteed to land."],
        spellIds: {"rank1":18094, "rank2":18095},
      },
      {
        id: 15,
        name: "Soul Siphon",
        icon: "spell_shadow_haunting",
        ranks: 3,
        row: 4,
        col: 4,
        description: ["Soul SiphonInstantIncreases the damage of your Drain Soul, Dark Harvest and Death Coil by an additional ",["$","$L22","1",{"tree":0,"talent":15,"values":["2","4","6"]}],"% for each of your Affliction effects on the target, up to a maximum of 4 effects."],
        spellIds: {"rank1":52558, "rank2":52559, "rank3":52560},
      },
      {
        id: 16,
        name: "Rapid Deterioration",
        icon: "spell_shadow_detectinvisibility",
        ranks: 2,
        row: 5,
        col: 1,
        requires: 17,
        description: ["Rapid DeteriorationInstantIncreases the casting speed of your Affliction spells by 6%. In addition, casting speed increase effects increase the tick speed of your damage over time and channeled Affliction spells with ",["$","$L22","1",{"tree":0,"talent":16,"values":["50","100"]}],"% efficiency, reducing their duration."],
        spellIds: {"rank1":52555, "rank2":52556},
      },
      {
        id: 17,
        name: "Siphon Life",
        icon: "spell_shadow_requiem",
        ranks: 1,
        row: 5,
        col: 2,
        description: "Siphon Life mana30 yd rangeInstantTransfers 15 Health from the target to the caster over 30 sec.",
        spellIds: {"rank1":18265},
      },
      {
        id: 18,
        name: "Improved Curse of Exhaustion",
        icon: "spell_shadow_grimward",
        ranks: 2,
        row: 5,
        col: 3,
        requires: 10,
        description: ["Improved Curse of ExhaustionInstantIncreases the speed reduction of your Curse of Exhaustion by ",["$","$L22","1",{"tree":0,"talent":18,"values":["15","30"]}],"%."],
        spellIds: {"rank1":18310, "rank2":18311},
      },
      {
        id: 19,
        name: "Malediction",
        icon: "spell_shadow_curseofachimonde",
        ranks: 1,
        row: 5,
        col: 4,
        description: "MaledictionInstantYour Curse of Agony can be used alongside your other curses, except Curse of Doom.\n\nApplying Curse of Recklessness, Curse of Shadows, or Curse of Elements also afflicts the target with the highest rank of your Curse of Agony.",
        spellIds: {"rank1":52546},
      },
      {
        id: 21,
        name: "Shadow Mastery",
        icon: "spell_shadow_shadetruesight",
        ranks: 5,
        row: 6,
        col: 2,
        description: ["Shadow MasteryInstantIncreases the damage dealt or life drained by your Shadow spells by ",["$","$L22","1",{"tree":0,"talent":21,"values":["2","4","6","8","10"]}],"%."],
        spellIds: {"rank1":18271, "rank2":18272, "rank3":18273, "rank4":18274, "rank5":18275},
      },
      {
        id: 25,
        name: "Dark Harvest",
        icon: "spell_shadow_soulleech",
        ranks: 1,
        row: 7,
        col: 2,
        requires: 21,
        description: "Dark Harvest mana30 yd rangeChanneledReaps the target's life, dealing 88 Shadow damage over 8 sec. While channeling, the time between periodic ticks of your Affliction spells on the target is reduced by 30%. If the target dies while channeling, the cooldown of Dark Harvest is reset.",
        spellIds: {"rank1":52550},
      }
    ],
  },
  demonology: {
    name: "Demonology",
    icon: "inv_stone_04",
    talents: [
      {
        id: 1,
        name: "Sinister Pursuit",
        icon: "ability_rogue_envelopingshadows",
        ranks: 2,
        row: 1,
        col: 2,
        description: "Sinister PursuitRank 1InstantIncreases the movement speed of your demons by 5% for 3 sec after they attack a target affected by Affliction effects.",
        spellIds: {"rank1":52737, "rank2":52739},
      },
      {
        id: 2,
        name: "Demonic Embrace",
        icon: "spell_shadow_metamorphosis",
        ranks: 5,
        row: 1,
        col: 3,
        description: ["Demonic EmbraceInstantIncreases your total Stamina by ",["$","$L22","1",{"tree":1,"talent":2,"values":["3","6","9","12","15"]}],"% but reduces your total Spirit by ",["$","$L22","2",{"tree":1,"talent":2,"values":["1","2","3","4","5"]}],"%."],
        spellIds: {"rank1":18697, "rank2":18698, "rank3":18699, "rank4":18700, "rank5":18701},
      },
      {
        id: 3,
        name: "Soul Entrapment",
        icon: "trade_archaeology_highbornesoulmirror",
        ranks: 3,
        row: 1,
        col: 4,
        description: ["Soul EntrapmentInstantWhile you have no demon under your control, all damage dealt is increased by ",["$","$L22","1",{"tree":1,"talent":3,"values":["2","4","6"]}],"%."],
        spellIds: {"rank1":51706, "rank2":51707, "rank3":51708},
      },
      {
        id: 4,
        name: "Soul Funnel",
        icon: "spell_shadow_lifedrain",
        ranks: 2,
        row: 2,
        col: 1,
        description: ["Soul FunnelInstantIncreases the amount of Health transferred by your Health Funnel by ",["$","$L22","1",{"tree":1,"talent":4,"values":["10","20"]}],"% of your demon's missing Health and the Mana transferred by your Mana Funnel by ",["$","$L22","2",{"tree":1,"talent":4,"values":["10","20"]}],"% of your demon's missing Mana. This additional transfer drains 30% of that amount from you."],
        spellIds: {"rank1":18703, "rank2":18704},
      },
      {
        id: 5,
        name: "Demonic Aegis",
        icon: "spell_shadow_ragingscream",
        ranks: 3,
        row: 2,
        col: 2,
        description: ["Demonic AegisInstantIncreases the effectiveness of your Demon Armor spell by ",["$","$L22","1",{"tree":1,"talent":5,"values":["20","40","60"]}],"%."],
        spellIds: {"rank1":45921, "rank2":45922, "rank3":45923},
      },
      {
        id: 6,
        name: "Fel Intellect",
        icon: "spell_holy_magicalsentry",
        ranks: 3,
        row: 2,
        col: 3,
        description: ["Fel IntellectInstantIncreases your demon's Intellect by ",["$","$L22","1",{"tree":1,"talent":6,"values":["10","20","30"]}],"% of your total Intellect and allows ",["$","$L22","2",{"tree":1,"talent":6,"values":["5","10","15"]}],"% of its Mana regeneration to continue while casting."],
        spellIds: {"rank1":18731, "rank2":18743, "rank3":18744},
      },
      {
        id: 9,
        name: "Fel Domination",
        icon: "spell_nature_removecurse",
        ranks: 1,
        row: 3,
        col: 2,
        description: "Fel DominationInstant300 sec cooldownYour next Common demon summoning spell has its casting time reduced by 4500 sec and its Mana cost reduced by 40%.",
        spellIds: {"rank1":18708},
      },
      {
        id: 10,
        name: "Fel Stamina",
        icon: "spell_shadow_antishadow",
        ranks: 5,
        row: 3,
        col: 3,
        description: ["Fel StaminaInstantIncreases your demon's Stamina by ",["$","$L22","1",{"tree":1,"talent":10,"values":["10","20","30","40","50"]}],"% of your total Stamina and reduces its chance to be critically struck by ",["$","$L22","2",{"tree":1,"talent":10,"values":["1","2","3","4","5"]}],"%."],
        spellIds: {"rank1":18748, "rank2":18749, "rank3":18750, "rank4":18751, "rank5":18752},
      },
      {
        id: 11,
        name: "Demonic Sacrifice",
        icon: "spell_shadow_psychicscream",
        ranks: 1,
        row: 3,
        col: 4,
        requires: 3,
        description: "Demonic Sacrifice100 yd rangeInstantWhen activated, sacrifices your summoned demon to grant you an effect. The effect is canceled if any demon is summoned or enslaved.\n\nImp: Increases spell damage done by 4%.\n\nVoidwalker: Restores 3% of total Health every 4 sec.\n\nSuccubus: Reduces threat generated by 10%.\n\nFelhunter: Restores 3% of total Mana every 4 sec.",
        spellIds: {"rank1":18788},
      },
      {
        id: 12,
        name: "Improved Stones",
        icon: "inv_jewelry_talisman_fireice",
        ranks: 2,
        row: 4,
        col: 1,
        description: ["Improved StonesInstantIncreases the effectiveness of your Felstone, Wrathstone, Voidstone, and Spellstone by ",["$","$L22","1",{"tree":1,"talent":12,"values":["25","50"]}],"%, and increases the critical strike chance bonus of your Firestone by ",["$","$L22","2",{"tree":1,"talent":12,"values":["50","100"]}],"%."],
        spellIds: {"rank1":51712, "rank2":51713},
      },
      {
        id: 13,
        name: "Master Summoner",
        icon: "spell_shadow_impphaseshift",
        ranks: 2,
        row: 4,
        col: 2,
        requires: 9,
        description: ["Master SummonerInstantReduces the casting time of your Imp, Voidwalker, Succubus and Felhunter summoning spells by ",["$","$L22","1",{"tree":1,"talent":13,"values":["2000","4000"]}]," sec and their Mana cost by ",["$","$L22","2",{"tree":1,"talent":13,"values":["30","60"]}],"%. In addition, reduces the cooldown of your Inferno and Demon Gate spells by ",["$","$L22","3",{"tree":1,"talent":13,"values":["25","50"]}],"%. Ritual of Doom: 3 sec initial cast, 2 sec summoner channel, requires 1 assisting summoner (was 2 total). Demon Gate's Felguard spawns 4 sec after the gate opens (was 6 sec)."],
        spellIds: {"rank1":18709, "rank2":18710},
      },
      {
        id: 14,
        name: "Nether Studies",
        icon: "inv_misc_book_06",
        ranks: 3,
        row: 4,
        col: 3,
        description: ["Nether StudiesInstantIncreases the effect of your Succubus' Seduction, your Voidwalker's Torment, your Imp's Blood Pact, and your Felhunter's Tainted Blood spells by ",["$","$L22","1",{"tree":1,"talent":14,"values":["15","30","45"]}],"%."],
        spellIds: {"rank1":51709, "rank2":51710, "rank3":51711},
      },
      {
        id: 15,
        name: "Unholy Power",
        icon: "spell_shadow_shadowworddominate",
        ranks: 3,
        row: 4,
        col: 4,
        description: ["Unholy PowerInstantIncreases the damage done by your demons by ",["$","$L22","1",{"tree":1,"talent":15,"values":["5","10","15"]}],"%."],
        spellIds: {"rank1":18769, "rank2":18770, "rank3":18771},
      },
      {
        id: 17,
        name: "Power Overwhelming",
        icon: "ability_warlock_power_overwhelming",
        ranks: 1,
        row: 5,
        col: 2,
        description: "Power Overwhelming80 manaInstant14 sec cooldownChannel energy into your demon, breaking all crowd control effects and increasing its damage dealt by 20% for 10 sec. The demon takes 40% of its base health as damage over the duration.",
        spellIds: {"rank1":51714},
      },
      {
        id: 18,
        name: "Demonic Precision",
        icon: "spell_shadow_curseoftounges",
        ranks: 3,
        row: 5,
        col: 3,
        description: ["Demonic PrecisionInstantYour demons ",["$","$L22","1",{"tree":1,"talent":18,"values":["1","2","3"]}],"% melee and spell hit chance and inherit ",["$","$L22","2",{"tree":1,"talent":18,"values":["30","60","90"]}],"% of your spell hit chance and spell critical chance as both melee and spell hit chance, and melee and spell critical chance, respectively."],
        spellIds: {"rank1":51715, "rank2":51716, "rank3":51717},
      },
      {
        id: 21,
        name: "Master Demonologist",
        icon: "spell_shadow_shadowpact",
        ranks: 5,
        row: 6,
        col: 2,
        description: ["Master DemonologistInstantGrants both the Warlock and the summoned demon an effect as long as that demon is active.\\n\\nImp - Reduces spell costs by ",["$","$L22","1",{"tree":1,"talent":21,"values":["3","6","9","12","15"]}],"%.\\n\\nVoidwalker - Reduces physical damage taken by ",["$","$L22","2",{"tree":1,"talent":21,"values":["2","4","6","8","10"]}],"%.\\n\\nSuccubus - Increases all damage done by ",["$","$L22","3",{"tree":1,"talent":21,"values":["2","4","6","8","10"]}],"%.\\n\\nFelhunter - Increases all resistances by 0.\\n\\nGreater Demons - Increases spell critical chance by ",["$","$L22","4",{"tree":1,"talent":21,"values":["2","4","6","8","10"]}],"%, but reduces healing received by ",["$","$L22","5",{"tree":1,"talent":21,"values":["8","16","24","32","40"]}],"%.\\n"],
        spellIds: {"rank1":23785, "rank2":23822, "rank3":23823, "rank4":23824, "rank5":23825},
      },
      {
        id: 22,
        name: "Unleashed Potential",
        icon: "ability_warlock_demonicpower",
        ranks: 3,
        row: 6,
        col: 3,
        description: ["Unleashed PotentialInstantYour direct damage spells allow your demon to benefit from ",["$","$L22","1",{"tree":1,"talent":22,"values":["5","10","15"]}],"% of your Fire and Shadow spell bonus damage for 20 sec. Each tick of your funnel spells refreshes its duration. Stacks up to 20001 times."],
        spellIds: {"rank1":51721, "rank2":51722, "rank3":51723},
      },
      {
        id: 25,
        name: "Soul Link",
        icon: "spell_shadow_gathershadows",
        ranks: 1,
        row: 7,
        col: 2,
        requires: 21,
        description: "Soul LinkPassiveInstantWhile a demon is under your control, the damage dealt by you and your demon is increased by 5%. In addition, 25% of all damage you take is taken by your demon. Your Greater and Enslaved Demons can no longer break free from your control early.",
        spellIds: {"rank1":19028},
      }
    ],
  },
  destruction: {
    name: "Destruction",
    icon: "spell_shadow_shadowbolt",
    talents: [
      {
        id: 1,
        name: "Shadow Vulnerability",
        icon: "spell_shadow_shadowbolt",
        ranks: 5,
        row: 1,
        col: 2,
        description: ["Shadow VulnerabilityInstantYour Shadow Bolt and Drain Soul have a ",["$","$L22","1",{"tree":2,"talent":1,"values":["2","4","6","8","10"]}],"% chance to increase Shadow damage dealt to the target by 20% for 10 sec, with a higher chance to trigger on critical hits."],
        spellIds: {"rank1":17793, "rank2":17796, "rank3":17801, "rank4":17802, "rank5":17803},
      },
      {
        id: 2,
        name: "Cataclysm",
        icon: "spell_fire_windsofwoe",
        ranks: 5,
        row: 1,
        col: 3,
        description: ["CataclysmInstantReduces the Mana cost of your Destruction spells by ",["$","$L22","1",{"tree":2,"talent":2,"values":["2","4","6","8","10"]}],"%."],
        spellIds: {"rank1":17778, "rank2":17779, "rank3":17780, "rank4":17781, "rank5":17782},
      },
      {
        id: 4,
        name: "Demonic Swiftness",
        icon: "spell_shadow_curseoftounges",
        ranks: 2,
        row: 2,
        col: 1,
        description: ["Demonic SwiftnessInstantReduces the casting time of your Imp's Firebolt spell by ",["$","$L22","1",{"tree":2,"talent":4,"values":["250","500"]}]," sec and reduces the cooldown of your Succubus' Lash of Pain spell by ",["$","$L22","2",{"tree":2,"talent":4,"values":["3000","6000"]}]," sec."],
        spellIds: {"rank1":57730, "rank2":57731},
      },
      {
        id: 5,
        name: "Bane",
        icon: "spell_shadow_deathpact",
        ranks: 5,
        row: 2,
        col: 2,
        description: ["BaneInstantReduces the casting time of your Shadow Bolt and Immolate spells by ",["$","$L22","1",{"tree":2,"talent":5,"values":["100","200","300","400","500"]}]," sec and your Soul Fire spell by ",["$","$L22","2",{"tree":2,"talent":5,"values":["400","800","1200","1600","2000"]}]," sec. Reduces the casting time of your Searing Pain spell by ",["$","$L22","3",{"tree":2,"talent":5,"values":["100","200","300","400","500"]}]," sec."],
        spellIds: {"rank1":17788, "rank2":17789, "rank3":17790, "rank4":17791, "rank5":17792},
      },
      {
        id: 6,
        name: "Aftermath",
        icon: "spell_fire_fire",
        ranks: 3,
        row: 2,
        col: 3,
        description: ["AftermathInstantIncreases the periodic damage of your Immolate spell by ",["$","$L22","1",{"tree":2,"talent":6,"values":["2","4","6"]}],"% and gives your Destruction spells a ",["$","$L22","2",{"tree":2,"talent":6,"values":["4","7","10"]}],"% chance to slow the target by 50% for 5 sec."],
        spellIds: {"rank1":18119, "rank2":18120, "rank3":18121},
      },
      {
        id: 8,
        name: "Intensity",
        icon: "spell_fire_lavaspawn",
        ranks: 2,
        row: 3,
        col: 1,
        description: ["IntensityInstantGives your Fire spells a ",["$","$L22","1",{"tree":2,"talent":8,"values":["35","70"]}],"% chance to not lose casting time when you take damage."],
        spellIds: {"rank1":18135, "rank2":18136},
      },
      {
        id: 9,
        name: "Shadowburn",
        icon: "spell_shadow_scourgebuild",
        ranks: 1,
        row: 3,
        col: 2,
        description: "Shadowburn mana20 yd rangeInstantReagents: Soul ShardInstantly blasts the target for 87 to 100 Shadow damage. If the target dies within 5 sec of Shadowburn, and yields experience or honor, the caster gains a Soul Shard.",
        spellIds: {"rank1":17877},
      },
      {
        id: 10,
        name: "Devastation",
        icon: "spell_fire_flameshock",
        ranks: 5,
        row: 3,
        col: 3,
        description: ["DevastationInstantIncreases the critical strike chance of your Destruction spells by ",["$","$L22","1",{"tree":2,"talent":10,"values":["1","2","3","4","5"]}],"%."],
        spellIds: {"rank1":18130, "rank2":18131, "rank3":18132, "rank4":18133, "rank5":18134},
      },
      {
        id: 12,
        name: "Pyroclasm",
        icon: "spell_fire_volcano",
        ranks: 2,
        row: 4,
        col: 1,
        requires: 8,
        description: ["PyroclasmInstantGives your Rain of Fire, Hellfire, Conflagrate, and Soul Fire spells a ",["$","$L22","1",{"tree":2,"talent":12,"values":["13","26"]}],"% chance to stun the target for 3 sec."],
        spellIds: {"rank1":18096, "rank2":18073},
      },
      {
        id: 13,
        name: "Destructive Reach",
        icon: "spell_shadow_corpseexplode",
        ranks: 2,
        row: 4,
        col: 2,
        description: ["Destructive ReachInstantIncreases the range of your Destruction spells by ",["$","$L22","1",{"tree":2,"talent":13,"values":["10","20"]}],"% and the radius of your Hellfire by ",["$","$L22","2",{"tree":2,"talent":13,"values":["10","20"]}],"%."],
        spellIds: {"rank1":17917, "rank2":17918},
      },
      {
        id: 15,
        name: "Improved Searing Pain",
        icon: "spell_fire_soulburn",
        ranks: 5,
        row: 4,
        col: 4,
        description: ["Improved Searing PainInstantSearing Pain's base damage was increased by approximately 20% (all ranks). Increases the critical strike chance of your Searing Pain spell by ",["$","$L22","1",{"tree":2,"talent":15,"values":["2","4","6","8","10"]}],"%."],
        spellIds: {"rank1":17927, "rank2":17929, "rank3":17930, "rank4":17931, "rank5":17932},
      },
      {
        id: 16,
        name: "Improved Soul Fire",
        icon: "spell_fire_fireball02",
        ranks: 2,
        row: 5,
        col: 1,
        description: ["Improved Soul FireInstantYour Soul Fire has a ",["$","$L22","1",{"tree":2,"talent":16,"values":["50","100"]}],"% chance to refund a Soul Shard and increase your Fire damage by 10% for 30 sec."],
        spellIds: {"rank1":51736, "rank2":51737},
      },
      {
        id: 17,
        name: "Improved Immolate",
        icon: "spell_fire_immolation",
        ranks: 5,
        row: 5,
        col: 2,
        description: ["Improved ImmolateInstantIncreases the damage of your Immolate spell by ",["$","$L22","1",{"tree":2,"talent":17,"values":["4","8","12","16","20"]}],"%."],
        spellIds: {"rank1":17815, "rank2":17833, "rank3":17834, "rank4":17835, "rank5":17836},
      },
      {
        id: 18,
        name: "Ruin",
        icon: "spell_shadow_shadowwordpain",
        ranks: 1,
        row: 5,
        col: 3,
        requires: 10,
        description: "RuinInstantIncreases the critical strike damage bonus of your Destruction spells by 100%.",
        spellIds: {"rank1":17959},
      },
      {
        id: 22,
        name: "Emberstorm",
        icon: "spell_fire_selfdestruct",
        ranks: 5,
        row: 6,
        col: 3,
        description: ["EmberstormInstantIncreases the damage done by your Fire spells by ",["$","$L22","1",{"tree":2,"talent":22,"values":["2","4","6","8","10"]}],"%."],
        spellIds: {"rank1":17954, "rank2":17955, "rank3":17956, "rank4":17957, "rank5":17958},
      },
      {
        id: 25,
        name: "Conflagrate",
        icon: "spell_fire_fireball",
        ranks: 1,
        row: 7,
        col: 2,
        requires: 17,
        description: "Conflagrate mana30 yd rangeInstantIgnites the target, dealing 240 to 307 Fire damage and consuming 3 sec of your Immolate spell to deal an amount of damage equal to it.",
        spellIds: {"rank1":17962},
      }
    ],
  },
};
