// Warrior talents for Turtle WoW
export const warriorTalents = {
    arms: {
        name: "Arms",
        icon: "ability_rogue_ambush",
        talents: [
            {
                id: 0,
                name: "Improved Heroic Strike",
                icon: "ability_rogue_ambush",
                ranks: 3,
                row: 1,
                col: 1,
                description: "Reduces the cost of your Heroic Strike ability by 10 rage point.",
                
                fullDescription: "Reduces the cost of your Heroic Strike ability by 10 rage point.",
                
                spellIds: [
                    12282,
                    12663,
                    12664
                ],
                rankDescriptions: [
                    "Reduces the cost of your Heroic Strike ability by 10 rage point.",
                    "Reduces the cost of your Heroic Strike ability by 20 rage points.",
                    "Reduces the cost of your Heroic Strike ability by 30 rage points."
                ]
            },
            {
                id: 1,
                name: "Tactical Mastery",
                icon: "spell_nature_enchantarmor",
                ranks: 5,
                row: 1,
                col: 2,
                description: "You retain up to 5 of your rage points when you change stances.",
                
                fullDescription: "You retain up to 5 of your rage points when you change stances.",
                
                spellIds: [
                    12295,
                    12676,
                    12677,
                    12678,
                    12679
                ],
                rankDescriptions: [
                    "You retain up to 5 of your rage points when you change stances.",
                    "You retain up to 10 of your rage points when you change stances.",
                    "You retain up to 20 of your rage points when you change stances.",
                    "You retain up to 25 of your rage points when you change stances.",
                    "You retain up to 5 of your rage points when you change stances."
                ]
            },
            {
                id: 2,
                name: "Improved Rend",
                icon: "ability_gouge",
                ranks: 2,
                row: 1,
                col: 3,
                description: "Increases the bleed damage done by your Rend ability by 10%.",
                
                fullDescription: "Increases the bleed damage done by your Rend ability by 10%.",
                
                spellIds: [
                    12286,
                    12658
                ],
                rankDescriptions: [
                    "Increases the bleed damage done by your Rend ability by 10%.",
                    "Increases the bleed damage done by your Rend ability by 20%."
                ]
            },
            {
                id: 4,
                name: "Improved Charge",
                icon: "ability_warrior_charge",
                ranks: 2,
                row: 2,
                col: 1,
                description: "Increases the amount of rage generated by your Charge ability by 5.",
                
                fullDescription: "Increases the amount of rage generated by your Charge ability by 5.",
                
                spellIds: [
                    12285,
                    12697
                ],
                rankDescriptions: [
                    "Increases the amount of rage generated by your Charge ability by 5.",
                    "Increases the amount of rage generated by your Charge ability by 10."
                ]
            },
            {
                id: 5,
                name: "Deflection",
                icon: "ability_parry",
                ranks: 5,
                row: 2,
                col: 2,
                description: "Increases your Parry chance by 1%.",
                
                fullDescription: "Increases your Parry chance by 1%.",
                
                spellIds: [
                    16462,
                    16463,
                    16464,
                    16465,
                    16466
                ],
                rankDescriptions: [
                    "Increases your Parry chance by 1%.",
                    "Increases your Parry chance by 2%.",
                    "Increases your Parry chance by 3%.",
                    "Increases your Parry chance by 4%.",
                    "Increases your Parry chance by 5%."
                ]
            },
            {
                id: 7,
                name: "Improved Thunder Clap",
                icon: "ability_thunderclap",
                ranks: 3,
                row: 2,
                col: 4,
                description: "Reduces the cost of your Thunder Clap ability by 10 rage point and increases the damage by 20%.",
                
                fullDescription: "Reduces the cost of your Thunder Clap ability by 10 rage point and increases the damage by 20%.",
                
                spellIds: [
                    12287,
                    12665,
                    12666
                ],
                rankDescriptions: [
                    "Reduces the cost of your Thunder Clap ability by 10 rage point and increases the damage by 20%.",
                    "Reduces the cost of your Thunder Clap ability by 20 rage point and increases the damage by 40%.",
                    "Reduces the cost of your Thunder Clap ability by 40 rage point and increases the damage by 60%."
                ]
            },
            {
                id: 8,
                name: "Master Strike",
                icon: "master_strike_1",
                ranks: 1,
                row: 3,
                col: 1,
                description: "Performs a skillful attack, dealing 35% weapon damage and causing an additional effect depending on your main hand weapon.\\n\\\\n\\n\\\\nMace: Disorients the target for 3 sec. Any damage caused will remove the effect.\\n\\\\n\\n\\\\nSword: Disarms the target for 3 sec.\\n\\\\n\\n\\\\nAxe: Immobilizes the target for 4 sec.\\n\\\\n\\n\\\\nPolearm: Deals an additional 100% weapon damage if the target is mounted and dismounts them.\\n\\\\n\\n\\\\nFist Weapon: Knocks down the target for 2 sec.\\n\\\\n\\n\\\\nStaff: Increases your chance to parry by 25% for 10 sec.\\n\\\\n\\n\\\\nDagger: Silences the target for 3 sec.",
                
                fullDescription: "Performs a skillful attack, dealing 35% weapon damage and causing an additional effect depending on your main hand weapon.\\n\\\\n\\n\\\\nMace: Disorients the target for 3 sec. Any damage caused will remove the effect.\\n\\\\n\\n\\\\nSword: Disarms the target for 3 sec.\\n\\\\n\\n\\\\nAxe: Immobilizes the target for 4 sec.\\n\\\\n\\n\\\\nPolearm: Deals an additional 100% weapon damage if the target is mounted and dismounts them.\\n\\\\n\\n\\\\nFist Weapon: Knocks down the target for 2 sec.\\n\\\\n\\n\\\\nStaff: Increases your chance to parry by 25% for 10 sec.\\n\\\\n\\n\\\\nDagger: Silences the target for 3 sec.",
                
                spellIds: [
                    54023
                ],
                rankDescriptions: [
                    "Performs a skillful attack, dealing 35% weapon damage and causing an additional effect depending on your main hand weapon.\\n\\\\n\\n\\\\nMace: Disorients the target for 3 sec. Any damage caused will remove the effect.\\n\\\\n\\n\\\\nSword: Disarms the target for 3 sec.\\n\\\\n\\n\\\\nAxe: Immobilizes the target for 4 sec.\\n\\\\n\\n\\\\nPolearm: Deals an additional 100% weapon damage if the target is mounted and dismounts them.\\n\\\\n\\n\\\\nFist Weapon: Knocks down the target for 2 sec.\\n\\\\n\\n\\\\nStaff: Increases your chance to parry by 25% for 10 sec.\\n\\\\n\\n\\\\nDagger: Silences the target for 3 sec."
                ]
            },
            {
                id: 9,
                name: "Improved Overpower",
                icon: "inv_sword_05",
                ranks: 2,
                row: 3,
                col: 2,
                description: "Increases the critical strike chance of your Overpower ability by 25%.",
                
                fullDescription: "Increases the critical strike chance of your Overpower ability by 25%.",
                
                spellIds: [
                    12290,
                    12963
                ],
                rankDescriptions: [
                    "Increases the critical strike chance of your Overpower ability by 25%.",
                    "Increases the critical strike chance of your Overpower ability by 50%."
                ]
            },
            {
                id: 10,
                name: "Deep Wounds",
                icon: "ability_backstab",
                ranks: 3,
                row: 3,
                col: 3,
                requires: 2,
                description: "Your critical strikes cause the opponent to bleed, dealing 20% of your melee weapon's average damage over 6 sec.",
                
                fullDescription: "Your critical strikes cause the opponent to bleed, dealing 20% of your melee weapon's average damage over 6 sec.",
                
                spellIds: [
                    12834,
                    12849,
                    12867
                ],
                rankDescriptions: [
                    "Your critical strikes cause the opponent to bleed, dealing 20% of your melee weapon's average damage over 6 sec.",
                    "Your critical strikes cause the opponent to bleed, dealing 40% of your melee weapon's average damage over 6 sec.",
                    "Your critical strikes cause the opponent to bleed, dealing 20% of your melee weapon's average damage over 6 sec."
                ]
            },
            {
                id: 13,
                name: "Two-Handed Weapon Specialization",
                icon: "inv_axe_09",
                ranks: 3,
                row: 4,
                col: 2,
                description: "Increases the damage you deal with two-handed melee weapons by 2% and increases your skill in all two-handed weapons by 1.",
                
                fullDescription: "Increases the damage you deal with two-handed melee weapons by 2% and increases your skill in all two-handed weapons by 1.",
                
                spellIds: [
                    12163,
                    12711,
                    12712
                ],
                rankDescriptions: [
                    "Increases the damage you deal with two-handed melee weapons by 2% and increases your skill in all two-handed weapons by 1.",
                    "Increases the damage you deal with two-handed melee weapons by 4% and increases your skill in all two-handed weapons by 2.",
                    "Increases the damage you deal with two-handed melee weapons by 6% and increases your skill in all two-handed weapons by 3."
                ]
            },
            {
                id: 14,
                name: "Impale",
                icon: "ability_searingarrow",
                ranks: 2,
                row: 4,
                col: 3,
                requires: 10,
                description: "Increases the critical strike damage bonus of your abilities in Battle, Defensive, and Berserker stance by 10%.",
                
                fullDescription: "Increases the critical strike damage bonus of your abilities in Battle, Defensive, and Berserker stance by 10%.",
                
                spellIds: [
                    16493,
                    16494
                ],
                rankDescriptions: [
                    "Increases the critical strike damage bonus of your abilities in Battle, Defensive, and Berserker stance by 10%.",
                    "Increases the critical strike damage bonus of your abilities in Battle, Defensive, and Berserker stance by 20%."
                ]
            },
            {
                id: 16,
                name: "Master of Arms",
                icon: "garrison_weaponupgrade",
                ranks: 5,
                row: 5,
                col: 1,
                requires: 8,
                description: "Adds the following effects to your weapons, based on the weapon type.\\n\\\\n\\n\\\\nAxe - Increases your chance to get a critical strike by 1%.\\n\\\\n\\n\\\\nMace - Causes your attacks to ignore 1.2 of your target's Armor per level.\\n\\\\n\\n\\\\nSword - Gives you a 1% chance to get an extra attack on the same target after hitting your target.\\n\\\\n\\n\\\\nPolearm - Increases the range of melee attacks by 0.4 yd.",
                
                fullDescription: "Adds the following effects to your weapons, based on the weapon type.\\n\\\\n\\n\\\\nAxe - Increases your chance to get a critical strike by 1%.\\n\\\\n\\n\\\\nMace - Causes your attacks to ignore 1.2 of your target's Armor per level.\\n\\\\n\\n\\\\nSword - Gives you a 1% chance to get an extra attack on the same target after hitting your target.\\n\\\\n\\n\\\\nPolearm - Increases the range of melee attacks by 0.4 yd.",
                
                spellIds: [
                    51644,
                    51655,
                    51656,
                    51657,
                    51658
                ],
                rankDescriptions: [
                    "Adds the following effects to your weapons, based on the weapon type:\\r\\\\n\\r\\\\nAxe - Increases your chance to get a critical strike by 1%.\\r\\\\nMace - Causes your attacks to ignore 1.2 of your target's Armor per level.\\r\\\\nSword - Gives you a 1% chance to get an extra attack on the same target after hitting your target.\\r\\\\nPolearm - Increases the range of melee attacks by 0.4 yd.",
                    "Adds the following effects to your weapons, based on the weapon type:\\r\\\\n\\r\\\\nAxe - Increases your chance to get a critical strike by 2%.\\r\\\\nMace - Causes your attacks to ignore 2.4 of your target's Armor per level.\\r\\\\nSword - Gives you a 2% chance to get an extra attack on the same target after hitting your target.\\r\\\\nPolearm - Increases the range of melee attacks by 0.8 yd.",
                    "Adds the following effects to your weapons, based on the weapon type:\\r\\\\n\\r\\\\nAxe - Increases your chance to get a critical strike by 3%.\\r\\\\nMace - Causes your attacks to ignore 3.6 of your target's Armor per level.\\r\\\\nSword - Gives you a 3% chance to get an extra attack on the same target after hitting your target.\\r\\\\nPolearm - Increases the range of melee attacks by 1.2 yd.",
                    "Adds the following effects to your weapons, based on the weapon type:\\r\\\\n\\r\\\\nAxe - Increases your chance to get a critical strike by 4%.\\r\\\\nMace - Causes your attacks to ignore 4.8 of your target's Armor per level.\\r\\\\nSword - Gives you a 4% chance to get an extra attack on the same target after hitting your target.\\r\\\\nPolearm - Increases the range of melee attacks by 1.6 yd.",
                    "Adds the following effects to your weapons, based on the weapon type:\\r\\\\n\\r\\\\nAxe - Increases your chance to get a critical strike by 5%.\\r\\\\nMace - Causes your attacks to ignore 6 of your target's Armor per level.\\r\\\\nSword - Gives you a 5% chance to get an extra attack on the same target after hitting your target.\\r\\\\nPolearm - Increases the range of melee attacks by 2. yd."
                ]
            },
            {
                id: 17,
                name: "Sweeping Strikes",
                icon: "ability_rogue_slicedice",
                ranks: 1,
                row: 5,
                col: 2,
                description: "Your next 5 abilities and main-hand melee attacks strike an additional nearby opponent.",
                
                fullDescription: "Your next 5 abilities and main-hand melee attacks strike an additional nearby opponent.",
                
                spellIds: [
                    12292
                ],
                rankDescriptions: [
                    "Your next 5 abilities and main-hand melee attacks strike an additional nearby opponent."
                ]
            },
            {
                id: 22,
                name: "Boundless Anger",
                icon: "ability_warrior_strengthofarms",
                ranks: 3,
                row: 5,
                col: 3,
                description: "Increases your maximum Rage by 10.",
                
                fullDescription: "Increases your maximum Rage by 10.",
                
                spellIds: [
                    57709,
                    57710,
                    57711
                ],
                rankDescriptions: [
                    "Increases your maximum Rage by 101.",
                    "Increases your maximum Rage by 201.",
                    "Increases your maximum Rage by 301."
                ]
            },
            {
                id: 23,
                name: "Improved Disciplines",
                icon: "ability_warrior_improveddisciplines",
                ranks: 3,
                row: 5,
                col: 4,
                description: "Reduces the cooldown of your Retaliation, Recklessness and Shield Wall abilities by 4 min.",
                
                fullDescription: "Reduces the cooldown of your Retaliation, Recklessness and Shield Wall abilities by 4 min.",
                
                spellIds: [
                    45576,
                    45577,
                    45578
                ],
                rankDescriptions: [
                    "Reduces the cooldown of your Retaliation, Recklessness and Shield Wall abilities by 4 min.",
                    "Reduces the cooldown of your Retaliation, Recklessness and Shield Wall abilities by 8 min.",
                    "Reduces the cooldown of your Retaliation, Recklessness and Shield Wall abilities by 12 min."
                ]
            },
            {
                id: 24,
                name: "Improved Slam",
                icon: "ability_warrior_decisivestrike",
                ranks: 2,
                row: 6,
                col: 1,
                description: "Reduces the cast time and global cooldown of your Slam ability by 0.25 sec.",
                
                fullDescription: "Reduces the cast time and global cooldown of your Slam ability by 0.25 sec.",
                
                spellIds: [
                    12862,
                    12330
                ],
                rankDescriptions: [
                    "Reduces the cast time and global cooldown of your Slam ability by 0.25 sec.",
                    "Reduces the cast time and global cooldown of your Slam ability by 0.25 sec."
                ]
            },
            {
                id: 26,
                name: "Precision Cut",
                icon: "ability_hunter_swiftstrike",
                ranks: 3,
                row: 6,
                col: 3,
                requires: 22,
                description: "Increases the base damage done by Execute by 15%.",
                
                fullDescription: "Increases the base damage done by Execute by 15%.",
                
                spellIds: [
                    51641,
                    51642,
                    51643
                ],
                rankDescriptions: [
                    "Increases the base damage done by Execute by 15%.",
                    "Increases the base damage done by Execute by 30%.",
                    "Increases the base damage done by Execute by 45%."
                ]
            },
            {
                id: 27,
                name: "Mortal Strike",
                icon: "ability_warrior_savageblow",
                ranks: 1,
                row: 7,
                col: 2,
                requires: 17,
                description: "A vicious strike that deals 115% weapon damage and wounds the target, reducing the effectiveness of any healing by 50% for 10 sec.",
                
                fullDescription: "A vicious strike that deals 115% weapon damage and wounds the target, reducing the effectiveness of any healing by 50% for 10 sec.",
                
                spellIds: [
                    12294
                ],
                rankDescriptions: [
                    "A vicious strike that deals 115% weapon damage and wounds the target, reducing the effectiveness of any healing by 50% for 10 sec."
                ]
            }
        ],
    },
    fury: {
        name: "Fury",
        icon: "spell_nature_purge",
        talents: [
            {
                id: 1,
                name: "Booming Voice",
                icon: "spell_nature_purge",
                ranks: 5,
                row: 1,
                col: 2,
                description: "Increases the area of effect of all shouts by 12% and the duration of your Battle and Demoralizing Shout by 12%.",
                
                fullDescription: "Increases the area of effect of all shouts by 12% and the duration of your Battle and Demoralizing Shout by 12%.",
                
                spellIds: [
                    12321,
                    12835,
                    12836,
                    12837,
                    12838
                ],
                rankDescriptions: [
                    "Increases the area of effect of all shouts by 12% and the duration of your Battle and Demoralizing Shout by 12%.",
                    "Increases the area of effect of all shouts by 24% and the duration of your Battle and Demoralizing Shout by 24%.",
                    "Increases the area of effect of all shouts by 36% and the duration of your Battle and Demoralizing Shout by 36%.",
                    "Increases the area of effect of all shouts by 48% and the duration of your Battle and Demoralizing Shout by 48%.",
                    "Increases the area of effect of all shouts by 60% and the duration of your Battle and Demoralizing Shout by 60%."
                ]
            },
            {
                id: 2,
                name: "Cruelty",
                icon: "ability_rogue_eviscerate",
                ranks: 5,
                row: 1,
                col: 3,
                description: "Increases your chance to get a critical strike with melee weapons by 1%.",
                
                fullDescription: "Increases your chance to get a critical strike with melee weapons by 1%.",
                
                spellIds: [
                    12320,
                    12852,
                    12853,
                    12855,
                    12856
                ],
                rankDescriptions: [
                    "Increases your chance to get a critical strike with melee weapons by 1%.",
                    "Increases your chance to get a critical strike with melee weapons by 2%.",
                    "Increases your chance to get a critical strike with melee weapons by 3%.",
                    "Increases your chance to get a critical strike with melee weapons by 4%.",
                    "Increases your chance to get a critical strike with melee weapons by 5%."
                ]
            },
            {
                id: 5,
                name: "Dual Wield Specialization",
                icon: "ability_dualwield",
                ranks: 5,
                row: 2,
                col: 2,
                description: "Increases the damage done by your offhand weapon by 5% and your chance to hit with your offhand weapon by 2%.",
                
                fullDescription: "Increases the damage done by your offhand weapon by 5% and your chance to hit with your offhand weapon by 2%.",
                
                spellIds: [
                    23584,
                    23585,
                    23586,
                    23587,
                    23588
                ],
                rankDescriptions: [
                    "Increases the damage done by your offhand weapon by 5% and your chance to hit with your offhand weapon by 2%.",
                    "Increases the damage done by your offhand weapon by 10% and your chance to hit with your offhand weapon by 4%.",
                    "Increases the damage done by your offhand weapon by 15% and your chance to hit with your offhand weapon by 6%.",
                    "Increases the damage done by your offhand weapon by 20% and your chance to hit with your offhand weapon by 8%.",
                    "Increases the damage done by your offhand weapon by 25% and your chance to hit with your offhand weapon by 10%."
                ]
            },
            {
                id: 6,
                name: "Unbridled Wrath",
                icon: "spell_nature_stoneclawtotem",
                ranks: 5,
                row: 2,
                col: 3,
                description: "Gives you a 15% chance to generate an additional Rage point when you deal melee damage with a weapon. The effect is doubled for two-handed weapons.",
                
                fullDescription: "Gives you a 15% chance to generate an additional Rage point when you deal melee damage with a weapon. The effect is doubled for two-handed weapons.",
                
                spellIds: [
                    12322,
                    12999,
                    13000,
                    13001,
                    13002
                ],
                rankDescriptions: [
                    "Gives you a 15% chance to generate an additional Rage point when you deal melee damage with a weapon. The effect is doubled for two-handed weapons.",
                    "Gives you a 30% chance to generate an additional Rage point when you deal melee damage with a weapon. The effect is doubled for two-handed weapons.",
                    "Gives you a 45% chance to generate an additional Rage point when you deal melee damage with a weapon. The effect is doubled for two-handed weapons.",
                    "Gives you a 60% chance to generate an additional Rage point when you deal melee damage with a weapon. The effect is doubled for two-handed weapons.",
                    "Gives you a 15% chance to generate an additional Rage point when you deal melee damage with a weapon. The effect is doubled for two-handed weapons."
                ]
            },
            {
                id: 8,
                name: "Improved Shouts",
                icon: "ability_warrior_commandingshout",
                ranks: 5,
                row: 3,
                col: 1,
                description: "Increases the melee attack power bonus of your Battle Shout by 5% and increases the melee attack power reduction of your Demoralizing Shout by 8%.",
                
                fullDescription: "Increases the melee attack power bonus of your Battle Shout by 5% and increases the melee attack power reduction of your Demoralizing Shout by 8%.",
                
                spellIds: [
                    51609,
                    51610,
                    51611,
                    51612,
                    51613
                ],
                rankDescriptions: [
                    "Increases the melee attack power bonus of your Battle Shout by 5% and increases the melee attack power reduction of your Demoralizing Shout by 8%.",
                    "Increases the melee attack power bonus of your Battle Shout by 15% and increases the melee attack power reduction of your Demoralizing Shout by 24%.",
                    "Increases the melee attack power bonus of your Battle Shout by 20% and increases the melee attack power reduction of your Demoralizing Shout by 32%.",
                    "Increases the melee attack power bonus of your Battle Shout by 5% and increases the melee attack power reduction of your Demoralizing Shout by 8%.",
                    "Increases the melee attack power bonus of your Battle Shout by 5% and increases the melee attack power reduction of your Demoralizing Shout by 8%."
                ]
            },
            {
                id: 9,
                name: "Piercing Howl",
                icon: "spell_shadow_deathscream",
                ranks: 1,
                row: 3,
                col: 2,
                description: "Causes all enemies near the warrior to be dazed, reducing movement speed by 50% for 6 sec.",
                
                fullDescription: "Causes all enemies near the warrior to be dazed, reducing movement speed by 50% for 6 sec.",
                
                spellIds: [
                    12323
                ],
                rankDescriptions: [
                    "Causes all enemies near the warrior to be dazed, reducing movement speed by 50% for 6 sec."
                ]
            },
            {
                id: 10,
                name: "Blood Craze",
                icon: "spell_shadow_summonimp",
                ranks: 3,
                row: 3,
                col: 3,
                description: "Regenerates 2% of your total Health over 6 sec after being the victim of a critical strike.",
                
                fullDescription: "Regenerates 2% of your total Health over 6 sec after being the victim of a critical strike.",
                
                spellIds: [
                    16487,
                    16489,
                    16492
                ],
                rankDescriptions: [
                    "Regenerates 2% of your total Health over 6 sec after being the victim of a critical strike.",
                    "Regenerates 4% of your total Health over 6 sec after being the victim of a critical strike.",
                    "Regenerates 2% of your total Health over 6 sec after being the victim of a critical strike."
                ]
            },
            {
                id: 13,
                name: "Battlefield Mobility",
                icon: "ability_rogue_sprint",
                ranks: 2,
                row: 4,
                col: 2,
                description: "Reduces the cooldown of your Intercept and Intervene abilities by 5 sec, and your Charge ability by 2 sec.",
                
                fullDescription: "Reduces the cooldown of your Intercept and Intervene abilities by 5 sec, and your Charge ability by 2 sec.",
                
                spellIds: [
                    20504,
                    20505
                ],
                rankDescriptions: [
                    "Reduces the cooldown of your Intercept and Intervene abilities by 5 sec, and your Charge ability by 2 sec.",
                    "Reduces the cooldown of your Intercept and Intervene abilities by 10 sec, and your Charge ability by 4 sec."
                ]
            },
            {
                id: 14,
                name: "Enrage",
                icon: "spell_shadow_unholyfrenzy",
                ranks: 5,
                row: 4,
                col: 3,
                description: "Gives you a 4% melee damage bonus for 8 sec after being the victim of a critical strike.",
                
                fullDescription: "Gives you a 4% melee damage bonus for 8 sec after being the victim of a critical strike.",
                
                spellIds: [
                    12317,
                    13045,
                    13046,
                    13047,
                    13048
                ],
                rankDescriptions: [
                    "Gives you a 4% melee damage bonus for 8 sec after being the victim of a critical strike.",
                    "Gives you a 8% melee damage bonus for 8 sec after being the victim of a critical strike.",
                    "Gives you a 12% melee damage bonus for 8 sec after being the victim of a critical strike.",
                    "Gives you a 16% melee damage bonus for 8 sec after being the victim of a critical strike.",
                    "Gives you a 4% melee damage bonus for 8 sec after being the victim of a critical strike."
                ]
            },
            {
                id: 15,
                name: "Improved Pummel",
                icon: "inv_gauntlets_04",
                ranks: 2,
                row: 4,
                col: 4,
                description: "Gives your Pummel ability a 50% chance to slow the victim for 4 sec. In addition, increases the duration of spellcasting school lockouts by 1 sec.",
                
                fullDescription: "Gives your Pummel ability a 50% chance to slow the victim for 4 sec. In addition, increases the duration of spellcasting school lockouts by 1 sec.",
                
                spellIds: [
                    51614,
                    51615
                ],
                rankDescriptions: [
                    "Gives your Pummel ability a 50% chance to slow the victim for 4 sec. In addition, increases the duration of spellcasting school lockouts by 1 sec.",
                    "Gives your Pummel ability a 100% chance to slow the victim for 4 sec. In addition, increases the duration of spellcasting school lockouts by 2 sec."
                ]
            },
            {
                id: 26,
                name: "Ravager",
                icon: "ability_whirlwind",
                ranks: 3,
                row: 5,
                col: 1,
                description: "Improved WhirlwindRank 1InstantReduces the cooldown of your Whirlwind ability by 1000 sec.",
                
                fullDescription: "Improved WhirlwindRank 1InstantReduces the cooldown of your Whirlwind ability by 1000 sec.",
                
                spellIds: [
                    51616,
                    51617,
                    51618
                ],
                rankDescriptions: [
                    "Improved WhirlwindRank 1InstantReduces the cooldown of your Whirlwind ability by 1000 sec.",
                    "Improved WhirlwindRank 1InstantReduces the cooldown of your Whirlwind ability by 1000 sec.",
                    "Improved WhirlwindRank 1InstantReduces the cooldown of your Whirlwind ability by 1000 sec."
                ]
            },
            {
                id: 27,
                name: "Death Wish",
                icon: "spell_shadow_deathpact",
                ranks: 1,
                row: 5,
                col: 2,
                description: "When activated, increases your physical damage by 20% and makes you immune to Fear effects, but lowers your armor and all resistances by 20%.  Lasts 30 sec.",
                
                fullDescription: "When activated, increases your physical damage by 20% and makes you immune to Fear effects, but lowers your armor and all resistances by 20%.  Lasts 30 sec.",
                
                spellIds: [
                    12328
                ],
                rankDescriptions: [
                    "When activated, increases your physical damage by 20% and makes you immune to Fear effects, but lowers your armor and all resistances by 20%.  Lasts 30 sec."
                ]
            },
            {
                id: 28,
                name: "Improved Execute",
                icon: "inv_sword_48",
                ranks: 2,
                row: 5,
                col: 4,
                description: "Reduces the Rage cost of your Execute ability by 20.",
                
                fullDescription: "Reduces the Rage cost of your Execute ability by 20.",
                
                spellIds: [
                    20502,
                    20503
                ],
                rankDescriptions: [
                    "Reduces the Rage cost of your Execute ability by 20.",
                    "Reduces the Rage cost of your Execute ability by 50."
                ]
            },
            {
                id: 29,
                name: "Improved Berserker Rage",
                icon: "spell_nature_ancestralguardian",
                ranks: 2,
                row: 6,
                col: 1,
                description: "Using Berserker Rage generates 50 Rage and grants a 50% chance to break free from movement impairing effects when activated.",
                
                fullDescription: "Using Berserker Rage generates 50 Rage and grants a 50% chance to break free from movement impairing effects when activated.",
                
                spellIds: [
                    20500,
                    20501
                ],
                rankDescriptions: [
                    "Using Berserker Rage generates 50 Rage and grants a 50% chance to break free from movement impairing effects when activated.",
                    "Using Berserker Rage generates 100 Rage and grants a 100% chance to break free from movement impairing effects when activated."
                ]
            },
            {
                id: 30,
                name: "Flurry",
                icon: "ability_ghoulfrenzy",
                ranks: 5,
                row: 6,
                col: 2,
                requires: 27,
                description: "Increases your attack speed by 10% for your next 3 swings after dealing a melee critical strike.",
                
                fullDescription: "Increases your attack speed by 10% for your next 3 swings after dealing a melee critical strike.",
                
                spellIds: [
                    12319,
                    12971,
                    12972,
                    12973,
                    12974
                ],
                rankDescriptions: [
                    "Increases your attack speed by 10% for your next 3 swings after dealing a melee critical strike.",
                    "Increases your attack speed by 10% for your next 3 swings after dealing a melee critical strike.",
                    "Increases your attack speed by 10% for your next 3 swings after dealing a melee critical strike.",
                    "Increases your attack speed by 10% for your next 3 swings after dealing a melee critical strike.",
                    "Increases your attack speed by 10% for your next 3 swings after dealing a melee critical strike."
                ]
            },
            {
                id: 31,
                name: "Blood Drinker",
                icon: "racial_troll_berserk",
                ranks: 3,
                row: 6,
                col: 3,
                requires: 14,
                description: "While affected by Enrage, Death Wish, or Recklessness, your melee attacks and abilities restore 1% of your maximum health.",
                
                fullDescription: "While affected by Enrage, Death Wish, or Recklessness, your melee attacks and abilities restore 1% of your maximum health.",
                
                spellIds: [
                    51623,
                    51624,
                    51625
                ],
                rankDescriptions: [
                    "While affected by Enrage, Death Wish, or Recklessness, your melee attacks and abilities restore 1% of your maximum health.",
                    "While affected by Enrage, Death Wish, or Recklessness, your melee attacks and abilities restore 1.5% of your maximum health.",
                    "While affected by Enrage, Death Wish, or Recklessness, your melee attacks and abilities restore 2% of your maximum health."
                ]
            },
            {
                id: 32,
                name: "Bloodthirst",
                icon: "spell_nature_bloodlust",
                ranks: 1,
                row: 7,
                col: 2,
                description: "Instantly perform a reckless attack, dealing 100 damage plus 35% of your Attack Power and increasing your movement speed by 10% for 6 sec.",
                
                fullDescription: "Instantly perform a reckless attack, dealing 100 damage plus 35% of your Attack Power and increasing your movement speed by 10% for 6 sec.",
                
                spellIds: [
                    23881
                ],
                rankDescriptions: [
                    "Instantly perform a reckless attack, dealing 100 damage plus 35% of your Attack Power and increasing your movement speed by 10% for 6 sec."
                ]
            }
        ],
    },
    protection: {
        name: "Protection",
        icon: "ability_racial_bloodrage",
        talents: [
            {
                id: 0,
                name: "Improved Bloodrage",
                icon: "ability_racial_bloodrage",
                ranks: 2,
                row: 1,
                col: 1,
                description: "Increases the instant Rage generated by your Bloodrage ability by 2.",
                
                fullDescription: "Increases the instant Rage generated by your Bloodrage ability by 2.",
                
                spellIds: [
                    12301,
                    12818
                ],
                rankDescriptions: [
                    "Increases the instant Rage generated by your Bloodrage ability by 2.",
                    "Increases the instant Rage generated by your Bloodrage ability by 5."
                ]
            },
            {
                id: 1,
                name: "Shield Specialization",
                icon: "inv_shield_06",
                ranks: 5,
                row: 1,
                col: 2,
                description: "Increases your chance to block attacks with a shield by 1% and generates 1 rage when a block occurs.",
                
                fullDescription: "Increases your chance to block attacks with a shield by 1% and generates 1 rage when a block occurs.",
                
                spellIds: [
                    12298,
                    12724,
                    12725,
                    12726,
                    12727
                ],
                rankDescriptions: [
                    "Increases your chance to block attacks with a shield by 1% and generates 1 rage when a block occurs.",
                    "Increases your chance to block attacks with a shield by 2% and generates 2 rage when a block occurs.",
                    "Increases your chance to block attacks with a shield by 3% and generates 3 rage when a block occurs.",
                    "Increases your chance to block attacks with a shield by 5% and generates 5 rage when a block occurs.",
                    "Increases your chance to block attacks with a shield by 1% and increases the amount blocked by 6%."
                ]
            },
            {
                id: 2,
                name: "Anticipation",
                icon: "spell_nature_mirrorimage",
                ranks: 3,
                row: 1,
                col: 3,
                description: "Increases your Defense by 7.",
                
                fullDescription: "Increases your Defense by 7.",
                
                spellIds: [
                    12297,
                    12750,
                    12751
                ],
                rankDescriptions: [
                    "Increases your Defense by 7.",
                    "Increases your Defense by 14.",
                    "Increases your Defense by 20."
                ]
            },
            {
                id: 5,
                name: "Iron Will",
                icon: "spell_magic_magearmor",
                ranks: 5,
                row: 2,
                col: 2,
                description: "Increases your chance to resist Stun and Charm effects by an additional 3%.",
                
                fullDescription: "Increases your chance to resist Stun and Charm effects by an additional 3%.",
                
                spellIds: [
                    12300,
                    12959,
                    12960,
                    12961,
                    12962
                ],
                rankDescriptions: [
                    "Increases your chance to resist Stun and Charm effects by an additional 3%.",
                    "Increases your chance to resist Stun and Charm effects by an additional 9%.",
                    "Increases your chance to resist Stun and Charm effects by an additional 12%.",
                    "Increases your chance to resist Stun and Charm effects by an additional 15%.",
                    "Increases your chance to resist Stun and Charm effects by an additional 3%."
                ]
            },
            {
                id: 6,
                name: "Toughness",
                icon: "spell_holy_devotion",
                ranks: 5,
                row: 2,
                col: 3,
                description: "Increases your armor value from items by 2%.",
                
                fullDescription: "Increases your armor value from items by 2%.",
                
                spellIds: [
                    12299,
                    12761,
                    12762,
                    12763,
                    12764
                ],
                rankDescriptions: [
                    "Increases your armor value from items by 2%.",
                    "Increases your armor value from items by 4%.",
                    "Increases your armor value from items by 6%.",
                    "Increases your armor value from items by 8%.",
                    "Increases your armor value from items by 10%."
                ]
            },
            {
                id: 8,
                name: "Last Stand",
                icon: "spell_holy_ashestoashes",
                ranks: 1,
                row: 3,
                col: 1,
                requires: 0,
                description: "When activated, this ability temporarily grants you 30% of your maximum hit points for 20 seconds.  After the effect expires, the hit points are lost.",
                
                fullDescription: "When activated, this ability temporarily grants you 30% of your maximum hit points for 20 seconds.  After the effect expires, the hit points are lost.",
                
                spellIds: [
                    12975
                ],
                rankDescriptions: [
                    "Instantly perform a reckless attack, dealing 100 damage plus 35% of your Attack Power and increasing your movement speed by 10% for 6 sec."
                ]
            },
            {
                id: 9,
                name: "Improved Intervene",
                icon: "ability_warrior_intervene",
                ranks: 2,
                row: 3,
                col: 2,
                description: "Grants a 50% chance to gain immunity to movement impairing effects for 3 sec after using Intervene.",
                
                fullDescription: "Grants a 50% chance to gain immunity to movement impairing effects for 3 sec after using Intervene.",
                
                spellIds: [
                    51591,
                    51592
                ],
                rankDescriptions: [
                    "Grants a 50% chance to gain immunity to movement impairing effects for 3 sec after using Intervene.",
                    "Grants a 100% chance to gain immunity to movement impairing effects for 3 sec after using Intervene."
                ]
            },
            {
                id: 10,
                name: "Improved Taunt",
                icon: "spell_nature_reincarnation",
                ranks: 2,
                row: 3,
                col: 3,
                description: "Reduces the cooldown of your Taunt ability by 1 sec.",
                
                fullDescription: "Reduces the cooldown of your Taunt ability by 1 sec.",
                
                spellIds: [
                    12302,
                    12765
                ],
                rankDescriptions: [
                    "Reduces the cooldown of your Taunt ability by 1 sec.",
                    "Reduces the cooldown of your Taunt ability by 2 sec."
                ]
            },
            {
                id: 11,
                name: "Improved Revenge",
                icon: "ability_warrior_revenge",
                ranks: 3,
                row: 3,
                col: 4,
                description: "Gives your Revenge ability a 15% chance to stun the target for 3 sec and reduces its cooldown by 0.5 sec.",
                
                fullDescription: "Gives your Revenge ability a 15% chance to stun the target for 3 sec and reduces its cooldown by 0.5 sec.",
                
                spellIds: [
                    12797,
                    12799,
                    12800
                ],
                rankDescriptions: [
                    "Gives your Revenge ability a 15% chance to stun the target for 3 sec and reduces its cooldown by 0.5 sec.",
                    "Gives your Revenge ability a 30% chance to stun the target for 3 sec and reduces its cooldown by 1 sec.",
                    "Gives your Revenge ability a 45% chance to stun the target for 3 sec and reduces its cooldown by 10.5 sec."
                ]
            },
            {
                id: 12,
                name: "Gag Order",
                icon: "ability_warrior_shieldbash",
                ranks: 2,
                row: 4,
                col: 1,
                description: "Your Shield Slam has an additional 50% chance to dispel 1 magic effect on the target and your Shield Bash ability has a 50% chance to silence the target for 3 sec.",
                
                fullDescription: "Your Shield Slam has an additional 50% chance to dispel 1 magic effect on the target and your Shield Bash ability has a 50% chance to silence the target for 3 sec.",
                
                spellIds: [
                    12311,
                    12958
                ],
                rankDescriptions: [
                    "Your Shield Slam has an additional 50% chance to dispel 1 magic effect on the target and your Shield Bash ability has a 50% chance to silence the target for 3 sec.",
                    "Your Shield Slam has an additional 50% chance to dispel 1 magic effect on the target and your Shield Bash ability has a 50% chance to silence the target for 3 sec."
                ]
            },
            {
                id: 13,
                name: "Improved Disarm",
                icon: "ability_warrior_disarm",
                ranks: 2,
                row: 4,
                col: 2,
                description: "Decreases the cooldown of your Disarm ability by 10 sec.",
                
                fullDescription: "Decreases the cooldown of your Disarm ability by 10 sec.",
                
                spellIds: [
                    12313,
                    12804
                ],
                rankDescriptions: [
                    "Decreases the cooldown of your Disarm ability by 10 sec.",
                    "Decreases the cooldown of your Disarm ability by 20 sec."
                ]
            },
            {
                id: 14,
                name: "Defiance",
                icon: "ability_warrior_innerrage",
                ranks: 5,
                row: 4,
                col: 3,
                description: "Increases the threat generated while in Defensive Stance by an additional 3%.",
                
                fullDescription: "Increases the threat generated while in Defensive Stance by an additional 3%.",
                
                spellIds: [
                    12303,
                    12788,
                    12789,
                    12791,
                    12792
                ],
                rankDescriptions: [
                    "Increases the threat generated while in Defensive Stance by an additional 3%.",
                    "Increases the threat generated while in Defensive Stance by an additional 6%.",
                    "Increases the threat generated while in Defensive Stance by an additional 9%.",
                    "Increases the threat generated while in Defensive Stance by an additional 12%.",
                    "Increases the threat generated while in Defensive Stance by an additional 15%."
                ]
            },
            {
                id: 16,
                name: "One-Handed Weapon Specialization",
                icon: "inv_sword_20",
                ranks: 5,
                row: 5,
                col: 1,
                description: "Increases the damage you deal with One-Handed Melee weapons by 2%.",
                
                fullDescription: "Increases the damage you deal with One-Handed Melee weapons by 2%.",
                
                spellIds: [
                    16538,
                    16539,
                    16540,
                    16541,
                    16542
                ],
                rankDescriptions: [
                    "Increases the damage you deal with One-Handed Melee weapons by 2%.",
                    "Increases the damage you deal with One-Handed Melee weapons by 4%.",
                    "Increases the damage you deal with One-Handed Melee weapons by 6%.",
                    "Increases the damage you deal with One-Handed Melee weapons by 8%.",
                    "Increases the damage you deal with One-Handed Melee weapons by 10%."
                ]
            },
            {
                id: 17,
                name: "Shield Slam",
                icon: "inv_shield_05",
                ranks: 1,
                row: 5,
                col: 2,
                description: "Slam the target with your shield, causing 174 to 185 damage, modified by your shield block value and attack power. This attack causes a high amount of threat, and has a 50% chance of dispelling 1 magic effect on the target.",
                
                fullDescription: "Slam the target with your shield, causing 174 to 185 damage, modified by your shield block value and attack power. This attack causes a high amount of threat, and has a 50% chance of dispelling 1 magic effect on the target.",
                
                spellIds: [
                    23922
                ],
                rankDescriptions: [
                    "Slam the target with your shield, causing 174 to 185 damage, modified by your shield block value and attack power. This attack causes a high amount of threat, and has a 50% chance of dispelling 1 magic effect on the target."
                ]
            },
            {
                id: 18,
                name: "Improved Shield Slam",
                icon: "ability_warrior_shieldmastery",
                ranks: 2,
                row: 5,
                col: 3,
                requires: 17,
                description: "Reduces the cooldown of your Shield Slam ability by 0.75 sec and increases your chance to block by 35% for 5 sec.",
                
                fullDescription: "Reduces the cooldown of your Shield Slam ability by 0.75 sec and increases your chance to block by 35% for 5 sec.",
                
                spellIds: [
                    51598,
                    51599
                ],
                rankDescriptions: [
                    "Reduces the cooldown of your Shield Slam ability by 0.75 sec and increases your chance to block by 35% for 5 sec.",
                    "Reduces the cooldown of your Shield Slam ability by 1.5 sec and increases your chance to block by 70% for 5 sec."
                ]
            },
            {
                id: 19,
                name: "Reprisal",
                icon: "ability_warrior_reprisal",
                ranks: 2,
                row: 5,
                col: 4,
                requires: 11,
                description: "Increases the damage dealt by your Revenge ability by 25%, and has a 50% chance to refund its rage cost if successful.",
                
                fullDescription: "Increases the damage dealt by your Revenge ability by 25%, and has a 50% chance to refund its rage cost if successful.",
                
                spellIds: [
                    51593,
                    51594
                ],
                rankDescriptions: [
                    "Increases the damage dealt by your Revenge ability by 25%, and has a 50% chance to refund its rage cost if successful.",
                    "Increases the damage dealt by your Revenge ability by 50%, and has a 100% chance to refund its rage cost if successful."
                ]
            },
            {
                id: 20,
                name: "Improved Shield Wall",
                icon: "ability_warrior_shieldwall",
                ranks: 2,
                row: 6,
                col: 1,
                description: "Increases the effect duration of your Shield Wall ability by 1 sec and reduces its cooldown by 300000 min.",
                
                fullDescription: "Increases the effect duration of your Shield Wall ability by 1 sec and reduces its cooldown by 300000 min.",
                
                spellIds: [
                    12312,
                    12803
                ],
                rankDescriptions: [
                    "Increases the effect duration of your Shield Wall ability by 1 sec and reduces its cooldown by 300000 min.",
                    "Increases the effect duration of your Shield Wall ability by 2 sec and reduces its cooldown by 600000 min."
                ]
            },
            {
                id: 22,
                name: "Defensive Tactics",
                icon: "ability_warrior_stalwartprotector",
                ranks: 3,
                row: 6,
                col: 3,
                description: "While wearing a shield, you retain 60% of the increased threat generation from Defensive Stance in other stances.",
                
                fullDescription: "While wearing a shield, you retain 60% of the increased threat generation from Defensive Stance in other stances.",
                
                spellIds: [
                    51606,
                    51607,
                    51608
                ],
                rankDescriptions: [
                    "While wearing a shield, you retain 60% of the increased threat generation from Defensive Stance in other stances.",
                    "While wearing a shield, you retain 120% of the increased threat generation from Defensive Stance in other stances.",
                    "While wearing a shield, you retain 180% of the increased threat generation from Defensive Stance in other stances."
                ]
            },
            {
                id: 25,
                name: "Concussion Blow",
                icon: "ability_thunderbolt",
                ranks: 1,
                row: 7,
                col: 2,
                requires: 17,
                description: "Deals 150 damage and stuns the opponent for 3 sec. This ability deals a high amount of threat and penetrates 100% of the enemy's armor. Instantly generates 10 rage.",
                
                fullDescription: "Deals 150 damage and stuns the opponent for 3 sec. This ability deals a high amount of threat and penetrates 100% of the enemy's armor. Instantly generates 10 rage.",
                
                spellIds: [
                    12809
                ],
                rankDescriptions: [
                    "Deals 150 damage and stuns the opponent for 3 sec. This ability deals a high amount of threat and penetrates 100% of the enemy's armor. Instantly generates 10 rage."
                ]
            }
        ],
    },
};
